### ISSUE TITLE
[Vacuum Cleaner] Improve rendering performance

### ISSUE THREAD

**Issue by SakshayMahna** [JdeRobot/RoboticsAcademy#1064]
In the exercises:
1. Vacuum Cleaner
2. Vacuum Cleaner with Localization

The rendering algorithm to display the area covered by robot is slow (Save visited points in a list and iterate list to render), which on prolonged execution, slows the browser down.

A smarter algorithm required for the task.

**Comment by dhrodao** [comment]
Issue created on [unibotics-exercises repo](https://github.com/JdeRobot/unibotics-exercises/issues/267)
