### ISSUE TITLE
Error while running the noetic image container

### ISSUE THREAD

**Issue by shashwat623** [JdeRobot/RoboticsAcademy#1079]
I get an error while starting a container for the latest noetic docker image. It seems it cannot locate the `start.sh` file from the mount point...

![Screenshot from 2021-07-01 12-45-47](https://user-images.githubusercontent.com/42846105/124082881-da5f4f80-da6a-11eb-9c90-61d03024a63e.png)

**Comment by pariaspe** [comment]
You can run it with:
```
docker run -it --device /dev/dri -p 8000:8000 -p 2303:2303 -p 1905:1905 -p 8765:8765 -p 6080:6080 -p 1108:1108 jderobot/robotics-academy:3.1.1 ./start-3.1.sh
```

**Comment by shashwat623** [comment]
Thanks @pariaspe . Should we change the noetic readme too then? It mentions `start.sh`

**Comment by pariaspe** [comment]
We'll better change script name

**Comment by shashwat623** [comment]
Alright @pariaspe
