### ISSUE TITLE
Fix typo Digit Classifier and frontend display

### ISSUE THREAD

**Issue by JuanManuelCarretero** [JdeRobot/RoboticsAcademy#1102]
Currently that exercise has a typo on the title card and the css for that exercise doesn't display as it should

**Comment by dpascualhe** [comment]
@JuanManuelCarretero thanks for the warning! I was working on another issue related to the digit classifier exercise. It'll be fixed asap.

**Comment by ReyDoran** [comment]
Closed by pr #1118
