### ISSUE TITLE
Update Car Junction webpage for RADI-3.1.3

### ISSUE THREAD

**Issue by vmartinezf** [JdeRobot/RoboticsAcademy#1116]
assigned @jessiffmm and @vmartinezf

**Comment by ReyDoran** [comment]
Closed by commit [b29d8daa7f582d4048d4aeedde28e536c6e40cfc](https://github.com/JdeRobot/RoboticsAcademy/commit/b29d8daa7f582d4048d4aeedde28e536c6e40cfc)
