### ISSUE TITLE
[gh-pages] Minor fix in exercise descriptions

### ISSUE THREAD

**Issue by JuanManuelCarretero** [JdeRobot/RoboticsAcademy#1129]
While creating the page for the Laser mapping exercise, I noticed that all current exercises in Robotics Academy still displayed on the webpage the explanation of Debug-Level and Frequency Sliders, things that have been replaced in newer versions of the RADI.

To avoid creating confussion to students, I have updated all exercise pages changing this section of the pages

**Comment by ReyDoran** [comment]
Closed by merged [pr-1130(https://github.com/JdeRobot/RoboticsAcademy/pull/1130)
