### ISSUE TITLE
Update Practices to use JdeRobotComm

### ISSUE THREAD

**Issue by aitormf** [JdeRobot/RoboticsAcademy#115]
We need update practices to use JdeRobotComm to be able to use ROS messages:

- [x] 3d_reconstruction
- [ ] bump_and_go_py
- [x] color_filter
- [ ] drone_cat_mouse
- [x] follow_line
- [x] follow_road
- [x] follow_turtlebot
- [x] global_navigation
- [ ] labyrinth_escape
- [x] obstacle_avoidance
- [x] position_control
- [x] rescue_people
- [ ] stop_practice
- [x] vaccum_practice
- [x] visual_lander

**Comment by jmplaza** [comment]
This issue is outdated and no longer relevant as the connecting interfaces between the robot drivers and the exercise templates are not ICE anymore but ROS, and only ROS. In the new design, the templates for all the RoboticsAcademy exercises are now ROS nodes.
