### ISSUE TITLE
[FollowLine] Add a keyboard teleoperator and a "teleoperator mode"

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#1177]
When done we may extend it to all the exercises, as it is an useful general functionality

**Comment by dhrodao** [comment]
Hello! I have just recently pushed the teleoperator mode functionality on issue-1177 branch.

**Comment by jmplaza** [comment]
Just create a Pull-Request against current master branch, it will contain your changes to solve this issue

**Comment by dhrodao** [comment]
Done!
