### ISSUE TITLE
Prototype of protection against syntactic errors in user's source code for the exercise at the web editor

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#1178]
Maybe using pylint (https://www.pylint.org/). The original user source code should not be sent to exercise.py in case of containing any Python syntatic errors. Maybe some warning message should be shown to the user...

**Comment by ReyDoran** [comment]
Branch [issue-1178](https://github.com/JdeRobot/RoboticsAcademy/tree/issue-1178) contains the work done so far. There is an issue though: HAL and GUI modules are not being detected by Pylint. Currently, those errors are being ignored, but this means that Pylint is not checking code related to HAL and GUI.
