### ISSUE TITLE
[gh-pages] Remove cache data in exercises folder

### ISSUE THREAD

**Issue by dpascualhe** [JdeRobot/RoboticsAcademy#1208]
@shashwat623 in the latest documentation update for the human detection exercise, some cache files were added by error (in this [commit](https://github.com/JdeRobot/RoboticsAcademy/commit/05960cb8c21058f47ac1febb6209517f22d5ba66)). All of the undesired binary files are stored inside an [exercises](https://github.com/JdeRobot/RoboticsAcademy/tree/gh-pages/exercises) folder that didn't exist before. Please remove this directory to get rid of them :pray: .

**Comment by shashwat623** [comment]
@dpascualhe Thanks for letting me know.

**Comment by jmplaza** [comment]
Fixed in #1209
