### ISSUE TITLE
[Follow Line] Add follow_line_game as part of the follow_line challenge

### ISSUE THREAD

**Issue by dhrodao** [JdeRobot/RoboticsAcademy#1217]
The code sent from Unibotics follow_line_game requesting for evaluation produced an error on importing HAL and GUI modules. So it's needed before to check if the exercise is part of the follow_line challenge, if it is, the path used will be the one for the follow_line challenge.
Also add the exercise "follow_line_game" to CIRCUIT_EX array.

**Comment by dhrodao** [comment]
The code sent from Unibotics follow_line_game requesting for evaluation produced an error on importing HAL and GUI modules. So it's needed before to check if the exercise is part of the follow_line challenge, if it is, the path used will be the one for the follow_line challenge.

**Comment by dhrodao** [comment]
Created PR

**Comment by ReyDoran** [comment]
Closed by #1221
