### ISSUE TITLE
Image path corrections in README files of few exercises

### ISSUE THREAD

**Issue by RUFFY-369** [JdeRobot/RoboticsAcademy#1235]
Please refer to PR #1234

**Comment by pariaspe** [comment]
Hi @RUFFY-369, README files are deprecated and do we not intend to keep them up to date. Current documentation can be found at the [webpage](https://jderobot.github.io/RoboticsAcademy/exercises/Drones/drone_cat_mouse).

**Comment by ReyDoran** [comment]
Closed as stated on previous comment
