### ISSUE TITLE
Delay in reloading the program to the brain

### ISSUE THREAD

**Issue by dvalladaresv** [JdeRobot/RoboticsAcademy#1332]

**Comment by jmplaza** [comment]
A new exercise.py template is needed for Vacuum Cleaner and Localized Vacuum Cleaner exercises to the second play work perfectly. Current template using only Python Threads keeps the first robot brain working a little bit after reloading...

In contrast, the FollowLine exercise has the latest exercise.py template. It uses Python subprocesses.
