### ISSUE TITLE
A new exercise: laser-based localization

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#1511]
A new exercise on Mobile Robots is available: "MonteCarlo laser-based robot localization". So it would be great to:
- [x] create a directory with the exercise template 
- [x] create its documentation webpage in GitHub Pages
- [x] add and entry in the exercise grid

The demo video is already available at our YouTube channel: https://www.youtube.com/watch?v=y7rBPpV2NdI

**Comment by dvalladaresv** [comment]
FIx
