### ISSUE TITLE
[Autoparking] improve the car used in this exercise

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#1605]
to follow Ackermann steering. Related to [https://github.com/JdeRobot/CustomRobots/issues/145](https://github.com/JdeRobot/CustomRobots/issues/145) and [https://github.com/JdeRobot/CustomRobots/issues/149](https://github.com/JdeRobot/CustomRobots/issues/149)

**Comment by BhaveshAnandpara** [comment]
Hey ! @antoniojromero are you working on this Issue ? I would like to contribute also!

**Comment by jmplaza** [comment]
Hi @BhaveshAnandpara , we are almost done with this issue, @akshaynarisetti has done a great job with it. Take a look at the latest video https://twitter.com/JdeRobot/status/1549634989255725057 from the last week. More info on this is available at [Akshay's GSoC page](https://theroboticsclub.github.io/gsoc2022-Akshay_Narisetti/) and [current week report](https://theroboticsclub.github.io/gsoc2022-Akshay_Narisetti/2022/07/24/Coding-Period-Week-8.html).

It will be soon available at [CustomRobots repository](https://github.com/JdeRobot/CustomRobots) and integrated in the autoparking exercise of RoboticsAcademy

**Comment by jmplaza** [comment]
Help with be needed @BhaveshAnandpara for creating nice and light Gazebo scenarios for this AutoParking exercise and for betatesting the exercise with the new car model :-)

**Comment by GauravKumar9920** [comment]
Hey, anyone working on this issue I would like to contribute on this issue.

**Comment by jmplaza** [comment]
HI @GauravKumar9920 ,
yes, @Amglega almost has solved it, take a look at his [demo video](https://www.youtube.com/watch?v=CucqZrXDOto) at JdeRobot's YouTube channel regarding his solution.
