### ISSUE TITLE
Discussion about exercise containing 2 web templates

### ISSUE THREAD

**Issue by Apoorvgarg-creator** [JdeRobot/RoboticsAcademy#1671]
According to the [RepositoryArchitecture.md](https://github.com/JdeRobot/RoboticsAcademy/blob/master/docs/RepositoryArchitecture.md) exercise.html is present in `/exercises/templates/exercises` But for some exercise for ex. Color filter exercise  [here](https://github.com/JdeRobot/RoboticsAcademy/tree/master/exercises/static/exercises/color_filter/web-template/WebRtc/web-template) also have exercise.html. I tried understanding the difference so I ran both on local server, and I know that they are different in look but I wanted to know when and how it is used ?
Can I know what's the difference between these two exercise.html ?

**Comment by pariaspe** [comment]
Hi @Apoorvgarg-creator, most of HTML files out of `/exercises/templates/exercises/` are unused and deprecated, so they are susceptible to be deleted. 
Thanks for noticing.

**Comment by Apoorvgarg-creator** [comment]
Thank you @pariaspe for the help

**Comment by jmplaza** [comment]
The confusion due to several web templates in some exercises will be solved in #1792

**Comment by GauravKumar9920** [comment]
Is this issue solved ?

**Comment by pariaspe** [comment]
Yes, it is solved. Thanks @GauravKumar9920
