### ISSUE TITLE
[Frontend] Hover effect on exercise card on Homepage

### ISSUE THREAD

**Issue by Apoorvgarg-creator** [JdeRobot/RoboticsAcademy#1674]
When hover on the exercise card, it shows blank card.

### Screen recording -

https://user-images.githubusercontent.com/57873504/163565828-b7d81a51-2377-4142-a3f1-8f8d00455ce1.mov

### Expected outcome -
A video must be played as per my understanding of the code below -
<img width="823" alt="Screenshot 2022-04-20 at 12 31 29 PM" src="https://user-images.githubusercontent.com/57873504/164169653-c94075ab-6b4a-415e-b8f4-3f063422595f.png">

**Comment by akshaynarisetti** [comment]
@Apoorvgarg-creator That is the expected behaviour. I have rechecked the code as well.

**Comment by Apoorvgarg-creator** [comment]
> @Apoorvgarg-creator That is the expected behaviour. I have rechecked the code as well.

Thank you @akshaynarisetti.
So, for what purpose this Video tag is placed here ?

**Comment by akshaynarisetti** [comment]
Hi @Apoorvgarg-creator

The pre-existing code had this concept of on-hover video playing feature, guess it was taking a lot of bandwidth.

From the code I can see that they clearly dropped this idea and replaced the video `src` with a `#` placeholder. So they didn’t want the video to play for some reason most probably above.

**Comment by Apoorvgarg-creator** [comment]
> Hi @Apoorvgarg-creator
> 
> The pre-existing code had this concept of on-hover video playing feature, guess it was taking a lot of bandwidth.
> 
> From the code I can see that they clearly dropped this idea and replaced the video `src` with a `#` placeholder. So they didn’t want the video to play for some reason most probably above.

Thank you for the help

**Comment by Apoorvgarg-creator** [comment]
@pariaspe Can I help in resolving this issue ? If yes, what should be the approach to solve the issue ?
Thank you

**Comment by AAYUSH-droid** [comment]
Hey can you assign this issue to me?

**Comment by pariaspe** [comment]
Yes @AAYUSH-droid, go ahead with it :+1:

**Comment by akshaynarisetti** [comment]
Hey @AAYUSH-droid, we are slowly adopting to react based templates. You may make changes there.

@dmariaa is working on it currently 😇

https://github.com/JdeRobot/RoboticsAcademy/discussions/1783

**Comment by r-Dev03** [comment]
Would love to tackle this issue

**Comment by pariaspe** [comment]
Hi @r-Dev03, thanks for your interest, we already implemented this on #1779
