### ISSUE TITLE
[manager 4.0] error gazebo stats

### ISSUE THREAD

**Issue by Carlosalpha1** [JdeRobot/RoboticsAcademy#1675]
Hi, I have a **problem** with [**manager-4.0.py**](https://github.com/JdeRobot/RoboticsAcademy/blob/foxy/scripts/manager-4.0.py) of foxy branch.  
When I launch my new exercise **Follow Person** the web-template crashes showing **Connecting 2...** indefinitely.

But, if I comment these lines, the **exercise** and **VNC** (with gazebo and terminal) work well.

![image](https://user-images.githubusercontent.com/60138826/164300395-1db0aebd-ab51-4990-818f-3359507ea480.png)  

I have tried to find the threads running using **pstree** command:  

![image](https://user-images.githubusercontent.com/60138826/164298917-d761eeb5-6c60-4e71-bbe7-a5868b184d6b.png)

Any idea what may be happening?
I think the problem is that the exercise needs a lot of **Gazebo resources** and using **gz stats** blocks the launch

Cheers!

**Comment by akshaynarisetti** [comment]
Hi @Carlosalpha1 
Did you try running that code in an individual thread?

**Comment by Tejal-19** [comment]
Yes, I think as it is running a subprocess, it is running multiple secondary processes. I think running an individual thread can be an option.

**Comment by jmplaza** [comment]
Manager-4.0.py was a nice prototype exploring ROS2 Foxy, but the new manager (=RAM, Robotics Application Manager) should be checked to know whether or not this error reporting Gazebo stats keeps bothering or not. That RAM will be used for ROS1-Noetic and for ROS2- Humble RADIs in the long run. Regarding ROS1-Noetic it is included in RADI-3.3.1 and available for the FollowLine exercise and the BasicVacuumCleaner exercise.

**Comment by jmplaza** [comment]
AFAIK the new manager, named RAM, is working fine in RADI 4.3.X and properly receiving the gazebo stats (such as Real Time Factor, RTF), which uses ROS2 Humble as reference. 

@Blancasr is this right?. In such case we could close this issue as solved.

**Comment by jmplaza** [comment]
Confirmed, it is working fine in ROS2 Humble RADI.
