### ISSUE TITLE
some css improvements

### ISSUE THREAD

**Issue by sumanparajuli** [JdeRobot/RoboticsAcademy#1766]
Hello sir,
I noticed in the website https://jderobot.github.io/RoboticsAcademy that the logo of google summer of code in the sponsor section is a bit left aligned when viewing from mobile device. it would be better if it was in center. I want to work on this sir. 
Thank You !!

**Comment by jmplaza** [comment]
Sure :-)

**Comment by pariaspe** [comment]
Fixed in #1767
