### ISSUE TITLE
Deprecated files 

### ISSUE THREAD

**Issue by Apoorvgarg-creator** [JdeRobot/RoboticsAcademy#1770]
There are many files in the path "exercises/static/exercises/assets/js" and also in web_templates/assets of exercise which are not used and deprecated.
Should I raise a PR removing all these deprecated files which causes problem to an exercise developers and other developers improving the front-end.

@dvalladaresv

**Comment by dvalladaresv** [comment]
Hello
Thanks for the report. If you want to create a PR to resolve this issue it would be helpful.

**Comment by Apoorvgarg-creator** [comment]
@dvalladaresv Thank you. I will complete the changes and raise a PR soon
