### ISSUE TITLE
[Drones] Rotors integration prototype

### ISSUE THREAD

**Issue by RUFFY-369** [JdeRobot/RoboticsAcademy#1773]
PR #1772 
Current exercises prototype with rotors integration: 

- [follow_turtlebot](http://jderobot.github.io/RoboticsAcademy/exercises/Drones/follow_turtlebot)
- [drone_cat_and_mouse](http://jderobot.github.io/RoboticsAcademy/exercises/Drones/drone_cat_mouse)

**Comment by jmplaza** [comment]
I guess we should also install some new dependencies (from rotorS) at the RADI...

**Comment by RUFFY-369** [comment]
Hi @jmplaza , the dependencies required by rotors are being installed in the new Dockerfile in rotors branch in the forked repo
