### ISSUE TITLE
[Documentation] Update documentation to add links help regular users and developer users

### ISSUE THREAD

**Issue by Apoorvgarg-creator** [JdeRobot/RoboticsAcademy#1776]
Developer user link - 
https://youtu.be/K_59Sxp9U_o   This link will be added in the docs directory of the repo

Regular user link -
https://youtu.be/dQ3JpuD-rbk    This link will be added in the Robotics academy web

**Comment by jmplaza** [comment]
Fixed in #1777 and #1780
