### ISSUE TITLE
Introduce a search box in the starting web page

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#1828]
So the users may search for a specific exercise by name, or even by tag. Maybe we may add some tags to attach to the exercise, to show its topic: autonomous driving, drones, mobile robots, service robots, computer vision, industrial robotics....

Once the user writes something in the search box, only the exercise matching it are displayed in the exercise grid.

**Comment by Apoorvgarg-creator** [comment]
@dmariaa Can I take the role of working on the search and tag functionality ?

**Comment by dmariaa** [comment]
Absolutly Yes @Apoorvgarg-creator .... I would consider adding a field to the exercise model in the Django backend, something like "tags"... then you can use that field in the backend and frontend like we do with the rest... Let me know if you need any help...

Thanks!!!!

**Comment by jmplaza** [comment]
Perfect. For the tags field in the exercise DabaBase we may have at least these tag names as possible values: Autonomous Driving, Service Robots, Drones, Computer Vision, Industrial Robots and DeepLearning, Mobile Robots. They cover all the currently existing exercises.

They are not disjoint. Each exercise may have attached one or more than one of them

**Comment by dmariaa** [comment]
BTW... Tags have to be maintained (added, modified, removed) in the /admin section of robotics academy, the list frontend need to have the possibility of being filtered by this tag, or searched by name...
