### ISSUE TITLE
[drone cat mouse]  Fix mouse configuration files

### ISSUE THREAD

**Issue by chanfr** [JdeRobot/RoboticsAcademy#184]
The configuration files included for cat mouse are not working.

**Comment by abhayraw1** [comment]
Actually there was a bug on the JdeRobot repository itself [#1099](https://github.com/JdeRobot/JdeRobot/issues/1099) was causing the error. The issue has been resolved and merged in that repository. Try updating it.
Hopefully it fixes things

**Comment by jmplaza** [comment]
solved with #525
