### ISSUE TITLE
Error while running Instructions for developers. Webpack-stats.json doesn't exist.

### ISSUE THREAD

**Issue by PabloAsensio** [JdeRobot/RoboticsAcademy#1849]
I've just clone the repo, I created a new local branch and I tried to follow [Instructions for developers](https://github.com/JdeRobot/RoboticsAcademy/blob/master/docs/InstructionsForDevelopers.md)

```RoboticsAcademy/react_frontend/webpack-stats.json``` is not in the repo.

I'm using Apple M2 chip.

**ERROR**
<img width="1450" alt="Screenshot 2022-11-06 at 19 15 49" src="https://user-images.githubusercontent.com/44872361/200188465-398ec723-6e0c-41de-89ea-f110d57caf7b.png">

**DOCKER**
<img width="1225" alt="Screenshot 2022-11-06 at 19 30 01" src="https://user-images.githubusercontent.com/44872361/200188667-f9b6dbaa-c533-493b-95f1-713ee229e556.png">

**ENV PYTHON PACKGES**
<img width="369" alt="Screenshot 2022-11-06 at 19 31 31" src="https://user-images.githubusercontent.com/44872361/200188652-e2fdfd30-7c51-4f13-abe8-324a62d16816.png">

What I need to do to run the http://127.0.0.1:8000/ properly?

**Comment by dvalladaresv** [comment]
You have to install the dependencies for react   (with Yarn or npm, required Node.JS >= 14.16)  
```
cd react_frontend/ && yarn install && yarn run dev    
```   
The documentation has just been improved by adding this part

**Comment by PabloAsensio** [comment]
Thanks. Only with ```cd react_frontend/ && yarn install ```  is fine. Also next step is usung python key word, not python3. We are using virtualenv
