### ISSUE TITLE
Problem with images in the FollowLine exercise with the new RAM

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#1895]
The Gazebo simulator starts properly the FollowLine scenario and the F1 car, and it provides the image ROS topic (checked with _rostopic echo_). The _exercise.py_ subscribes to that topic, but it does not create well the shared memory to store the received images from the car camera. It has not the proper size to store the frames...

>             self.shm_region = SharedMemory(self.shm_name)
>             self.shm_buf = mmap.mmap(self.shm_region.fd, size)
>             self.shm_region.close_fd()

Surprisingly, the same code is working fine with the current _manager.py_, with the images and the corresponding shared memory running smoothly like a charm.

**Comment by pariaspe** [comment]
Solved #1913
