### ISSUE TITLE
[Documentation] Description of current manager.py

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#1897]
In English and markdown format

**Comment by felicidadaqm** [comment]
Basic version added on the branch issue-1897.

Pending giving it a better format and adding a few more explanations about some functions. Tomorrow 11/01 will be completed and then I'll create the corresponding pull request with master branch.

**Comment by felicidadaqm** [comment]
Pull request created to merge the updated documentation: https://github.com/JdeRobot/RoboticsAcademy/pull/1927

**Comment by jmplaza** [comment]
Fixed in #1927
