### ISSUE TITLE
Minor changes to REACT client

### ISSUE THREAD

**Issue by ango1994** [JdeRobot/RoboticsAcademy#1922]
- Remove the ability to change brain and GUI frequency.
- Remove connect and launch button. Exercise launches automatically once the page is loaded.
- DIssable buttons while mesagges are sent between the client and the RAM to prevent duplicated communications.

**Comment by jmplaza** [comment]
Regarding connect and launch buttons I would remove them from the frontend, so the users are not required to click on them. But I would keep a simplified version of them, maybe simple red/green lights, to show the "status". A LED showing whether the browser and the docker are connected (green) or not (red). Anotther LED showing whether the exercise scenario has been properly launched (green) or not yet (red).
