### ISSUE TITLE
Migrate Global Navigation exercise to new RAM + REACT design

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#1947]

**Comment by Bhardwaj-Himanshu** [comment]
Hey @jmplaza @ango1994 @Apoorvgarg-creator, I know this section has already assignee's assigned to it!
But if I could provide any kind of help, I would love to do so!

Does Migrate Global Navigation here implies--converting the codebase according to new react code of conduct?

**Comment by Apoorvgarg-creator** [comment]
Hello @Bhardwaj-Himanshu, The exercise is already migrated with New RAM.

**Comment by Bhardwaj-Himanshu** [comment]
Thanks for letting me know @Apoorvgarg-creator!

**Comment by ango1994** [comment]
CLosed on #2181
