### ISSUE TITLE
[gh-pages] Update GPU acceleration launch instructions 

### ISSUE THREAD

**Issue by pariaspe** [JdeRobot/RoboticsAcademy#1957]
See #1950

**Comment by AsRaNi1** [comment]
Hi, I would please like to work on this issue

**Comment by pariaspe** [comment]
Hi @AsRaNi1, go ahead and suggest a PR with your solution. I'll review it. You can follow our contribution [guide](https://github.com/JdeRobot/RoboticsAcademy/blob/master/CONTRIBUTING.md).

**Comment by AsRaNi1** [comment]
@pariaspe I am working with the gh-pages branch, I had some questions:
- The website on my local machine and the one hosted (https://jderobot.github.io/) are different, are the gh pages on some other branch?
- Also to clear, i need to update the GPU acceleration launch instructions for each exercise right?

**Comment by jmplaza** [comment]
you are mixing things @AsRaNi1. The GitHub pages for RoboticsAcademy are shown at http://jderobot.github.io/RoboticsAcademy/ and created at the gh-pages branch of the RoboticsAcademy repo https://github.com/JdeRobot/RoboticsAcademy.

Yes, just update the GPU acceleration launch instructions for each exercise.

**Comment by AsRaNi1** [comment]
> you are mixing things @AsRaNi1. The GitHub pages for RoboticsAcademy are shown at http://jderobot.github.io/RoboticsAcademy/ and created at the gh-pages branch of the RoboticsAcademy repo https://github.com/JdeRobot/RoboticsAcademy.
> 
> Yes, just update the GPU acceleration launch instructions for each exercise.

Thank you!
That clears it 😅

**Comment by pariaspe** [comment]
Done in #1958
