### ISSUE TITLE
Minor frontend refinements for FollowLine+React+RAM exercise

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#1964]
- [x] Sim viewer activated by default and shown in the top part of the right side of the page
- [x] RTF and measured BrainFreq in the second horizontal bar. No third horizontal bar at the footer anymore
- [x] world selector in the first horizontal bar, aside the "Ready LED"
- [x] "View Camera" label ----> GUI. So it can be used in all exercises
- [x] "View Console" label ----> Console
- [x] swap of "Theory" and "Code" buttons at the first horizontal bar
- [x] Execution buttons: Play/Pause and Reset, both with icons instead of texts. The Play and Pause will be together in the same button, showing one or another icon depending on the 'state' of the execution
- [x] Disabling buttons (simulator/console) until 'launch'

**Comment by ango1994** [comment]
HI @yashphalle! I'm already working on this issue

**Comment by yashphalle** [comment]
> HI @yashphalle! I'm already working on this issue

Okk no problem!
Let me know if there is something that I can do or help you!
