### ISSUE TITLE
Add RAM port to launch instructions

### ISSUE THREAD

**Issue by pariaspe** [JdeRobot/RoboticsAcademy#1976]
```bash
docker run --rm -it -p 8000:8000 -p 2303:2303 -p 1905:1905 -p 8765:8765 -p 6080:6080 -p 1108:1108 -p 7163:7163 jderobot/robotics-academy
```

**Comment by pawanw17** [comment]
Hi I was thinking instead of updating every command individually whenever there's a change in command, we could have it saved in a single file and import the command from the file in all the exercises. This way whenever there's a change in the command in future we'll only have to update one file

**Comment by pariaspe** [comment]
It is a good idea but I don't know if it is possible
