### ISSUE TITLE
[Enhancement] Hyperlink the JdeRobot Logo to homepage

### ISSUE THREAD

**Issue by pawanw17** [JdeRobot/RoboticsAcademy#1998]
Currently to go back to exercises home in the RADI we have to use the back button of the browser, It'd be good if we could instead use the JDE Robot logo to do so.

![image](https://user-images.githubusercontent.com/40732709/230314667-387a9a42-f628-49af-a06f-3f1f999e2d1a.png)

**Comment by pariaspe** [comment]
Thanks @pawanw17

**Comment by damodardatta** [comment]
Hi,

I haven't been able to go back to the main page from exercises by pressing the logo while using the latest docker image.  Can you check if this repeats?

**Comment by pariaspe** [comment]
Hi @damodardatta , please try with tags 3.4.30 and 4.4.32 instead of latest

**Comment by damodardatta** [comment]
@pariaspe I've tried with the tags you suggested. I'm still not able to go back.

**Comment by pariaspe** [comment]
Ok, reopening then

**Comment by OscarMrZ** [comment]
Solved at #2467

**Comment by pawanw17** [comment]
Reopening this because of the superthin refactoring

**Comment by CDAM2020** [comment]
Made the pr #2524 fixing this

**Comment by jmplaza** [comment]
Solved in #2524
