### ISSUE TITLE
[Drone Hangar Exercise] Unable to launch Drone Hangar exercise correctly

### ISSUE THREAD

**Issue by pawanw17** [JdeRobot/RoboticsAcademy#1999]
To reproduce just launch the [drone hangar exercise](https://jderobot.github.io/RoboticsAcademy/exercises/Drones/drone_hangar) in the RADI.

Errors in logs:
![image](https://user-images.githubusercontent.com/40732709/230319279-2f56981e-0eb5-48f0-986f-a756f1d85d90.png)
 
![image](https://user-images.githubusercontent.com/40732709/230319595-6514915a-82ae-4f39-96e4-596496ea1b8c.png)

The issue is likely related to Gazebo not launching correctly and crashing.

**Comment by pariaspe** [comment]
Not finding cylinder model?
![drone_hangar](https://user-images.githubusercontent.com/35956525/232542411-67dd0633-8f11-4e5a-b9e4-81b30c84d8cd.png)

**Comment by pawanw17** [comment]
Hi @pariaspe the issue here is of missing models, 
Here's what happens

1. The first Gazebo instance runs 
2. Waits to download the models 
3. Timeout occurs
4. That's when a second instance is started by launch.py
5. The two instances eventually crash each other.

**Comment by pawanw17** [comment]
The exercise tries to download these models but is unable to find them
![image](https://user-images.githubusercontent.com/40732709/232641963-1295d8ed-e7bb-463a-9a5d-ac18b6de4e9b.png)

**Comment by pariaspe** [comment]
Got it @pawanw17 , the problem is this unmerged [PR](https://github.com/JdeRobot/drones/pull/183). The thing is that some parts of the PR are wanted and others unwanted. We still have to modify some parts of it.

**Comment by pariaspe** [comment]
Solved in JdeRobot/drones#188
