### ISSUE TITLE
Catkin Build failed packages in RADI

### ISSUE THREAD

**Issue by pawanw17** [JdeRobot/RoboticsAcademy#2006]
The catkin build command inside the RADI results in the failure of these 4 packages:

1. dataspeed_can_usb
2. dataspeed_can_tools
3. dbw_mkz_joystick_demo
4. dbw_mkz_twist_controller

Along with 20 packages which are abandoned during the build

![image](https://user-images.githubusercontent.com/40732709/232360376-96bae694-7a96-4af1-a515-f689fa9d8d4c.png)
![image](https://user-images.githubusercontent.com/40732709/232360429-73ee2b27-0d89-4909-9e47-a7b34de9cb1d.png)

If any exercise uses these, then it may have issues else if these are not needed anymore then can be removed.

**Comment by pariaspe** [comment]
Hi @pawanw17 , I'm able to build the RADI without facing that error. Could you provide some extra indications to reproduce the error?

**Comment by Amglega** [comment]
Not really, they are in the same directory as the Catvehicle package but are not used in the autoparking_v2 exercise because the car does not need to be teleoperated.
