### ISSUE TITLE
Some links redirecting to a 404 page

### ISSUE THREAD

**Issue by Bhardwaj-Himanshu** [JdeRobot/RoboticsAcademy#2025]
**Description of Issue**
While clicking through the documentation guidelines as well as contribution guidelines, link [documentation guide lines](https://jderobot.github.io/RoboticsAcademy/contribute/) is broken inside `contributing.md`.

https://user-images.githubusercontent.com/74407676/235203274-fee4d14d-419d-41d4-9a2b-3cc1a52d4de9.mp4

**What impact this change could cause?**
Causing a state of confusion and less retention of new users looking forward to work on the website.

**Fix?**
Just changing the links in `contributing.md` to new [Contributor Guide](https://jderobot.github.io/RoboticsAcademy/developer_guide)

**Comment by jmplaza** [comment]
Fixed in #2029
