### ISSUE TITLE
When starting the "jderobot/robotics-academy:latest" the port redirects at 0:0:0:8000/

### ISSUE THREAD

**Issue by Bhardwaj-Himanshu** [JdeRobot/RoboticsAcademy#2032]
**Issue**
![image](https://user-images.githubusercontent.com/74407676/235411045-cf5dcb29-87d4-4b2f-8f89-e6fe8ec5e332.png)

**Steps to reproduce**
Launch an instance of docker container `jderobot/robotics-academy:latest` , the port redirects to https://0.0.0.8000/

**Expected Behaviour**
Should show instance deployed at https://127.0.0.1:8000/

**Comment by pawanw17** [comment]
http://0.0.0.0:8000/ works for me.

**Comment by Bhardwaj-Himanshu** [comment]
Is my port 0:0:0:8000 alloted to something else? If yes could I check it or reallot the port the site listens to?
