### ISSUE TITLE
[Bump&Go_py] the pose3D should be included in the sensor API available for students

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#207]
The position interface (encoders, pose3D) should be included in the sensors API of this exercise. This way the rotations may be truly random and reactive: when entering into the "Rotate" state the current orientation is read and then a random 'target orientation' is set. For the following next iterations the transition will check whether or not the 'target orientation' has been achieved. The robot will continue turning until that happens.

**Comment by javizqh** [comment]
With the current implementation using hal_interfaces this info can be obtained from HAL.getPose3d()
