### ISSUE TITLE
[localized vacuum cleaner] png map file missing

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#2070]
It should be in "RoboticsAcademy/exercises/static/exercises/vacuum_cleaner_loc/resources/images/mapgrannyannie.png", but currently it is misplaced at "RoboticsAcademy/exercises/static/exercises/vacuum_cleaner_newmanager/resources/images/mapgrannyannie.png"

**Comment by ango1994** [comment]
Solved on #2076
