### ISSUE TITLE
[Follow Line RR] Exercise crashes when trying to change track

### ISSUE THREAD

**Issue by pawanw17** [JdeRobot/RoboticsAcademy#2071]
RADI: 3.4.2
![image](https://github.com/JdeRobot/RoboticsAcademy/assets/40732709/b4a3ed49-5cca-4217-b95b-83807b5cf671)

![image](https://github.com/JdeRobot/RoboticsAcademy/assets/40732709/dd51657c-5a36-47a9-8895-06c97931264e)

Logs: 

> Exercise initializing
HAL initializing
[ INFO] [1684443329.358606485]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1684443329.359752891]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 172.17.0.2
HAL initialized
Exercise initialized
[Msg] Loading world file [/RoboticsAcademy/exercises/static/exercises/follow_line/launch/prototype_f1_circuit_headless_default.world]
[ INFO] [1684443329.750165316]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1684443329.767721068]: Physics dynamic reconfigure ready.
HAL thread starting
Starting HAL thread
Client connected
[ INFO] [1684443330.860538517]: Camera Plugin: The 'robotNamespace' param did not exit
[ INFO] [1684443330.864552137]: Camera Plugin (ns = )  <tf_prefix_>, set to ""
[ INFO] [1684443330.878259610]: PlanarMovePlugin missing <robotNamespace>, defaults to ""
[ WARN] [1684443330.878358790]: PlanarMovePlugin (ns = ) missing <cmdTimeout>, defaults to -1.000000
{'id': 1, 'handler': <websocket_server.websocket_server.WebSocketHandler object at 0x7fc324335070>, 'address': ('127.0.0.1', 47850)} connected
GUI Process Started!
Brain Process Started!
{'id': 1, 'handler': <websocket_server.websocket_server.WebSocketHandler object at 0x7f922423ef70>, 'address': ('127.0.0.1', 60272)} closed
{'id': 1, 'handler': <websocket_server.websocket_server.WebSocketHandler object at 0x7fc324335070>, 'address': ('127.0.0.1', 47850)} closed
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/RoboticsAcademy/exercises/static/exercises/follow_line_newmanager/entry_point/../python_template/ros1_noetic/gui.py", line 244, in run_gui
    self.gui.update_gui()
  File "/RoboticsAcademy/exercises/static/exercises/follow_line_newmanager/entry_point/../python_template/ros1_noetic/gui.py", line 123, in update_gui
    self.server.send_message(self.client, message)
  File "/usr/local/lib/python3.8/dist-packages/websocket_server/websocket_server.py", line 78, in send_message
    self._unicast(client, msg)
  File "/usr/local/lib/python3.8/dist-packages/websocket_server/websocket_server.py", line 195, in _unicast
    receiver_client['handler'].send_message(msg)
  File "/usr/local/lib/python3.8/dist-packages/websocket_server/websocket_server.py", line 344, in send_message
    self.send_text(message)
  File "/usr/local/lib/python3.8/dist-packages/websocket_server/websocket_server.py", line 413, in send_text
    self.request.send(header + payload)
BrokenPipeError: [Errno 32] Broken pipe
[gazebo-2] killing on exit
terminate called after throwing an instance of 'boost::wrapexcept<boost::lock_error>'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
Aborted (core dumped)
[rosout-1] killing on exit
[master] killing on exit
Waiting for ROS and Gazebo to shutdown
121: Process already terminated [Errno 3] No such process
118: Process already terminated [Errno 3] No such process
151: Process already terminated [Errno 3] No such process
... logging to /root/.ros/log/5e7992d8-f5be-11ed-8f62-0242ac110002/roslaunch-0e52cf187a80-46.log

**Comment by ReyDoran** [comment]
Thanks for the report, it is now fixed (although it is not included in the RADI 3.4.1 yet) and it now depends on the available configurations on the database rather being hardcoded.
