### ISSUE TITLE
[mini RADI] Docker build commands in build.sh uses cached git repositories

### ISSUE THREAD

**Issue by pawanw17** [JdeRobot/RoboticsAcademy#2088]
The docker build command in [build.sh](https://github.com/JdeRobot/RoboticsAcademy/blob/c72417bc33e7f8e4f7946e8332c9ee8616508a48/scripts/mini_RADI/build.sh#L23) uses cached git repositories. So any newer commits on the same branch will not be used when building the mini RADI, which is a problem when testing patches.

I noticed this by building the mini RADI twice on different days and seeing the git logs of RoboticsAcademy

**Comment by ango1994** [comment]
Solved on #2090
