### ISSUE TITLE
[Follow_person] Add teleoperable person

### ISSUE THREAD

**Issue by Blancasr** [JdeRobot/RoboticsAcademy#2096]

**Comment by jmplaza** [comment]
It is linked to https://github.com/JdeRobot/RoboticsInfrastructure/issues/226. Here we should include a "world file" to be used in the FollowPerson exercise. The "world file" should launch the Gazebo world and the keyboard driver (which receives pressed keys from the browser). 

It would be great if the RoboticsAcademy user may select a world file with a complete autonomous moving person (to be followed by the robot), and an alternative world file with a person which has to be teleoperated by the user from the keyboard. This way the exercise would be even more fun :-)
