### ISSUE TITLE
[New exercise] Amazon warehouse exercise 

### ISSUE THREAD

**Issue by Blancasr** [JdeRobot/RoboticsAcademy#2107]

**Comment by ReyDoran** [comment]
Amazon Warehouse exercise is now merged in master to prevent further deviation from the master branch code.
- [ ] Fix OMPL import errors
- [ ] Fix World 2 map loading

**Comment by ReyDoran** [comment]
OMPL import errors solved in https://github.com/JdeRobot/RoboticsApplicationManager/pull/104

**Comment by ReyDoran** [comment]
World 2 map loading fixed in https://github.com/JdeRobot/RoboticsInfrastructure/pull/340
