### ISSUE TITLE
[Rescue people] missing asset for Haar cascade filter to detect human faces

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#2137]
"RoboticsAcademy/exercises/static/exercises/rescue_people_react/haarcascade_frontalface_default.xml" should be copied to "RoboticsAcademy/exercises/static/exercises/rescue_people/haarcascade_frontalface_default.xml" in order to get the classic version of this exercise also operative. It was wrongly removed some time ago.

**Comment by ango1994** [comment]
Closed on #2140
