### ISSUE TITLE
Files selector is disabled after the exercise ran once

### ISSUE THREAD

**Issue by lu164** [JdeRobot/RoboticsAcademy#2142]
The files selector is disabled after the exercise ran once, it turns gray and doesn't let me choose again.

- Running
![files_selector1](https://github.com/JdeRobot/RoboticsAcademy/assets/78978037/a67d3a65-3969-4ed8-b695-6f68885f991a)

- Stopped
![files_selector2](https://github.com/JdeRobot/RoboticsAcademy/assets/78978037/6d29b156-a2e8-43f8-84e4-235a003a3620)

**Comment by ango1994** [comment]
Fixed on #2199
