### ISSUE TITLE
[Noetic] Dependencies_noetic docker build crashing

### ISSUE THREAD

**Issue by pawanw17** [JdeRobot/RoboticsAcademy#2178]
Failing at this line
https://github.com/JdeRobot/RoboticsAcademy/blob/30178b55910840d0d002e0117657f6242f0cc6ba/scripts/mini_RADI/Dockerfile.dependencies_noetic#L55

Download link no longer working

EDIT: This mirror is working https://sourceforge.net/projects/turbovnc/files/3.0/turbovnc_3.0_amd64.deb/download?use_mirror=versaweb

**Comment by Bhardwaj-Himanshu** [comment]
Hi @pawanw17 , replacing it with a particular version would cause us to replace it every single time a new version is released!

But the general link as mentioned by you above is failing, could we replace it with something else in a longer run?And sticking to the 3.0 for now.

**Comment by pawanw17** [comment]
@Bhardwaj-Himanshu the version we use has been 3.0 for a while, and hasn't been upgraded to the latest version (I don't think we require an upgrade), I suggest to have .deb file inside the repository, the way it is done for Humble RADI, you can make a PR for this...

**Comment by Bhardwaj-Himanshu** [comment]
I have created a pull request, should we update the line after as well?
https://github.com/JdeRobot/RoboticsAcademy/blob/30178b55910840d0d002e0117657f6242f0cc6ba/scripts/mini_RADI/Dockerfile.dependencies_noetic#L56-L57
and if not, could you tell me on why?

**Comment by pawanw17** [comment]
Hi @Bhardwaj-Himanshu I meant to have the deb file locally saved in the gpu folder and change the install instructions in the Dockerfile making them similar to how Humble dockerfile installs turbovnc,

**Comment by Tanishq30052002** [comment]
Hi @pawanw17 ,
It seems the issue is still there, since currently also using that same link in the master branch. So should it need a correction?

**Comment by jmplaza** [comment]
Noetic branch is now deprecated, and ROS2 Humble is the only supported release now
