### ISSUE TITLE
yarn run dev failing

### ISSUE THREAD

**Issue by pawanw17** [JdeRobot/RoboticsAcademy#2190]
recent change in npm/yarn versions could have caused this failure
![image](https://github.com/JdeRobot/RoboticsAcademy/assets/40732709/490269c9-7571-4c9a-8865-f55766e9e5c6)

@ango1994

**Comment by ango1994** [comment]
HI @pawanw17 can you try reinstalling the dependencies? npm install or yarn install

**Comment by pawanw17** [comment]
Hi @ango1994, seeing the same issue on a fresh clone of Robotics Academy, inside react_frontend I ran 

yarn install
yarn run dev

**Comment by pawanw17** [comment]
Fixed by #2191
