### ISSUE TITLE
[Humble] Changing the World in Followine RR or Followperson RR not working

### ISSUE THREAD

**Issue by pawanw17** [JdeRobot/RoboticsAcademy#2193]
![image](https://github.com/JdeRobot/RoboticsAcademy/assets/40732709/d3416c36-8e19-4c61-8e98-1a9e6b898874)

> 2023-07-22 13:11:21,750 [MainThread  ] [INFO ] (root)  Terminating 0
> 2023-07-22 13:11:21,770 [MainThread  ] [INFO ] (root)  Terminating 1
> 2023-07-22 13:11:21,773 [MainThread  ] [INFO ] (root)  Terminating 2
> 2023-07-22 13:11:21,808 [MainThread  ] [INFO ] (transitions.core)  Executed callback 'on_terminate'
> 2023-07-22 13:11:21,808 [MainThread  ] [INFO ] (transitions.core)  Finished processing state ready exit callbacks.
> 2023-07-22 13:11:21,808 [MainThread  ] [INFO ] (root)  Connect state entered
> 2023-07-22 13:11:21,808 [MainThread  ] [INFO ] (transitions.core)  Executed callback 'on_enter_connected'
> 2023-07-22 13:11:21,808 [MainThread  ] [INFO ] (transitions.core)  Finished processing state connected enter callbacks.
> 2023-07-22 13:11:21,808 [MainThread  ] [INFO ] (root)  State changed to connected
> 2023-07-22 13:11:21,808 [MainThread  ] [INFO ] (transitions.core)  Executed callback '<bound method Manager.state_change of <__main__.Manager object at 0x7fef178118a0>>'
> 2023-07-22 13:11:21,809 [MainThread  ] [ERROR] (root)  Exception terminating instance
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/psutil/_common.py", line 441, in wrapper
>     ret = self._cache[fun]
> AttributeError: 'Process' object has no attribute '_cache'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1661, in wrapper
>     return fun(self, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/psutil/_common.py", line 444, in wrapper
>     return fun(self)
>   File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1703, in _parse_stat_file
>     with open_binary("%s/%s/stat" % (self._procfs_path, self.pid)) as f:
>   File "/usr/lib/python3/dist-packages/psutil/_common.py", line 711, in open_binary
>     return open(fname, "rb", **kwargs)
> FileNotFoundError: [Errno 2] No such file or directory: '/proc/1916/stat'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 361, in _init
>     self.create_time()
>   File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 717, in create_time
>     self._create_time = self._proc.create_time()
>   File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1661, in wrapper
>     return fun(self, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1873, in create_time
>     ctime = float(self._parse_stat_file()['create_time'])
>   File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1668, in wrapper
>     raise NoSuchProcess(self.pid, self._name)
> psutil.NoSuchProcess: process no longer exists (pid=1916)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "//RoboticsAcademy/src/manager/manager/manager.py", line 189, in on_disconnect
>     self.application.terminate()
>   File "/RoboticsAcademy/src/manager/libs/applications/compatibility/exercise_wrapper_ros2.py", line 161, in terminate
>     stop_process_and_children(self.exercise_server)
>   File "/RoboticsAcademy/src/manager/libs/process_utils.py", line 40, in stop_process_and_children
>     proc = psutil.Process(process.pid)
>   File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 332, in __init__
>     self._init(pid)
>   File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 373, in _init
>     raise NoSuchProcess(pid, msg='process PID not found')
> psutil.NoSuchProcess: process PID not found (pid=1916)
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/psutil/_common.py", line 441, in wrapper
>     ret = self._cache[fun]
> AttributeError: 'Process' object has no attribute '_cache'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1661, in wrapper
>     return fun(self, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/psutil/_common.py", line 444, in wrapper
>     return fun(self)
>   File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1703, in _parse_stat_file
>     with open_binary("%s/%s/stat" % (self._procfs_path, self.pid)) as f:
>   File "/usr/lib/python3/dist-packages/psutil/_common.py", line 711, in open_binary
>     return open(fname, "rb", **kwargs)
> FileNotFoundError: [Errno 2] No such file or directory: '/proc/1916/stat'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 361, in _init
>     self.create_time()
>   File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 717, in create_time
>     self._create_time = self._proc.create_time()
>   File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1661, in wrapper
>     return fun(self, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1873, in create_time
>     ctime = float(self._parse_stat_file()['create_time'])
>   File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1668, in wrapper
>     raise NoSuchProcess(self.pid, self._name)
> psutil.NoSuchProcess: process no longer exists (pid=1916)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "//RoboticsAcademy/src/manager/manager/manager.py", line 189, in on_disconnect
>     self.application.terminate()
>   File "/RoboticsAcademy/src/manager/libs/applications/compatibility/exercise_wrapper_ros2.py", line 161, in terminate
>     stop_process_and_children(self.exercise_server)
>   File "/RoboticsAcademy/src/manager/libs/process_utils.py", line 40, in stop_process_and_children
>     proc = psutil.Process(process.pid)
>   File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 332, in __init__
>     self._init(pid)
>   File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 373, in _init
>     raise NoSuchProcess(pid, msg='process PID not found')
> psutil.NoSuchProcess: process PID not found (pid=1916)
>

**Comment by ango1994** [comment]
Solved on https://github.com/JdeRobot/RoboticsApplicationManager/pull/66
