### ISSUE TITLE
Exercise doc button and forum button better open a new window 

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#2230]
... instead of opening at the same tab, hiding the code+execution page. This way the webpage with the user's source code remains ready to use, and the user experience is improved.

A new window maybe better than a new tab, as people with two screens may also benefit from it using one window for the code+execution webpage and another one for the user documentation for that RoboticsAcademy exercise (HAL API description, GUI API description)

**Comment by ango1994** [comment]
Closed on #2236

**Comment by pawanw17** [comment]
Reopening this because of the superthin refactoring

**Comment by espilya** [comment]
@pawanw17 I tested the exercises and didnt find this issue in them

**Comment by pawanw17** [comment]
@espilya closing this
