### ISSUE TITLE
Laser readings broken at Basic Vacuum Cleaner exercise

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#2231]
![fallo-laser](https://github.com/JdeRobot/RoboticsAcademy/assets/10961573/3e068af5-103b-4081-8cd4-a5903f1df027)

**Comment by aravind-reddy** [comment]
I think the correct way would be to follow for i in range(179):
As in python the index starts from 0 and ends at 180-1

**Comment by ReyDoran** [comment]
The reason is that the first readings of the sensors are empty, since the brain is running some iterations before Gazebo physics unpause. I'm pushing here and at RoboticsApplicationManager the fixes.
