### ISSUE TITLE
[ObstacleAvoidance] Laser sensor at Formula1 car slowly tilts down

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#2235]
and so it no longer detects further obstacles at the end of the circuit. Related to https://github.com/JdeRobot/RoboticsInfrastructure/issues/319

**Comment by ReyDoran** [comment]
Closed by [JdeRobot/RoboticsInfrastructure#319](https://github.com/JdeRobot/RoboticsInfrastructure/issues/319)
