### ISSUE TITLE
[Basic Vacuum Cleaner and Localized Vacuum Cleaner] Problem with the start point in the map

### ISSUE THREAD

**Issue by jessiffmm** [JdeRobot/RoboticsAcademy#2242]
The starting point on the map changes when you press play. Always start at one point and then switch to the correct starting point.

https://github.com/JdeRobot/RoboticsAcademy/assets/15524618/be3da20e-d146-4c08-a1e1-770e60c55a0f

**Comment by jmplaza** [comment]
We could also change the default location of the observation camera in the Gazebo Viewer (down right side of the webpage), to make it the same (compatible) with the orientation of the house in the display at the upper right side of the webapage. With the user experience will be better.

**Comment by ReyDoran** [comment]
Both problems solved in pr #2255
