### ISSUE TITLE
[VacuumCleaner-loc] The world file should be included in the resources directory of the REACT flavor 

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#2257]
also in the REACT flavor of the exercise, not only in the classic one. The apartment map (a png image) should be available for the users, and accessible from the user source code. The user source code has to read that map image and process it in order to solve the exercise.

Currently it is stored at https://github.com/JdeRobot/RoboticsAcademy/blob/master/exercises/static/exercises/vacuum_cleaner_loc/resources/images/mapgrannyannie.png
And so, the user may read it with: 
`map_img = cv2.imread('RoboticsAcademy/exercises/static/exercises/vacuum_cleaner_loc/resources/images/mapgrannyannie.png')
`
Now it should be copied at vacuum_cleaner_loc_newmanager directory and be accessible from there too.

**Comment by javizqh** [comment]
This has already been solved
