### ISSUE TITLE
Exercises execution usually does not stop when closing the main window.

### ISSUE THREAD

**Issue by fqez** [JdeRobot/RoboticsAcademy#226]
It happens in some academy exercises that when you try to stop the program by closing the main window of the GUI, the window closes but the process does not die properly or gets stuck forcing the user to use Ctrl + z and a kill command in the terminal.

**Comment by jmplaza** [comment]
This is related to previous 2.0 and 2.1 releases of RoboticsAcademy. It makes no sense in the web-based design of RoboticsAcademy 2.3
