### ISSUE TITLE
[Obstacle Avoidance]: possible error in displaying the target using GUI.showLocalTarget() function

### ISSUE THREAD

**Issue by amadridano** [JdeRobot/RoboticsAcademy#2284]
Good morning, 

Testing the operation of the OBstacle Avoindace exercise, I think I have found a possible error when displaying the target. 

According to the exercise documentation, the local axes of the car are: X forward, Y positive to the left. Therefore, I understand that the showLocalTarget() function should display the target in convenience with these axes. 

I have been testing with different pairs of points and the results obtained do not make sense to me, interpreting the exercise as described above. 

I am attaching screenshots. 

Translated with www.DeepL.com/Translator (free version)

Point[1,3]
![Screenshot from 2023-10-13 11-13-00](https://github.com/JdeRobot/RoboticsAcademy/assets/102746030/22ef7670-c20a-462b-b171-0884ecf694d6)

Point[3,1]
![Screenshot from 2023-10-13 11-12-43](https://github.com/JdeRobot/RoboticsAcademy/assets/102746030/e22d7cab-9685-466b-9d6a-747f84736e16)

Point [3,0]
![Screenshot from 2023-10-13 11-12-28](https://github.com/JdeRobot/RoboticsAcademy/assets/102746030/4b45cc6f-372d-4261-8c0a-027e50bca52d)

**Comment by ango1994** [comment]
Closed on #2288
