### ISSUE TITLE
[Obstacle Avoidance] improvements in the forces GUI display

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#2299]
- [ ] the car should not be red, as the repulsive forces are already red, and so they are not distinguished. Maybe gold+black, as the current F1 car.
- [ ] the car should be located in the center of the display, not in the lower part. This way the repulsive forces will be properly displayed, they usually point to the rear part of the car as the laser sensor is looking forward
- [ ] 10m and 25m are wrong, they should be replaced by real distances in meters. They can be estimated according to the laser sensor readings.

**Comment by AnushkaGharage** [comment]
1. I have changed the color to gold
2. Located the car in the center

I didn't quite understand the third issue. Will you please elaborate on that more?

**Comment by jmplaza** [comment]
Sure @AnushkaGharage ,

the 10m and 25m rectangles at the current frontend are not located in true real distances.
![obstacle-avoidance-frontend](https://github.com/JdeRobot/RoboticsAcademy/assets/10961573/4e0f7f5a-5856-4d3b-8078-cc7edce11be9) They should be replaced with the real distances, and maybe moved a little bit to "round numbers".

Could you share a snapshot of the frontend with your changes?

**Comment by AnushkaGharage** [comment]
@jmplaza I tried running 'yarn run dev' and it shows following error -
"""
ERROR in ./src/exercise-index.js 91:19-62
Module not found: Error: Can't resolve 'exercises' in 'C:\Users\ghara\OneDrive\Desktop\RADI\RoboticsAcademy\react_frontend\src'
"""
WebpackError at /exercises/
            ModuleNotFoundError in 
            Module not found: Error: Can't resolve 'exercises' in 'C:\Users\ghara\OneDrive\Desktop\RADI\RoboticsAcademy\react_frontend\src'
"""
But there is no directory inside src named exercises
So I am trying to find a solution for this error.
I will definitely get back once I solve the error.

**Comment by damodardatta** [comment]
![Screenshot from 2024-03-29 18-09-22](https://github.com/JdeRobot/RoboticsAcademy/assets/33845372/5461057f-bae1-451f-9adf-3e289ea8d1c6)
Hey @jmplaza,
        I have changed the color of the position of arrows and laser scans, but i'm not sure about how to move the rectangles(10m and 25m) or convert their scale.

**Comment by jmplaza** [comment]
Well done @damodardatta. The rectangles are wrong now, their motivation is to show to the student an estimate of the real distances around the car. Maybe 10m and 25m are too far, and the good numbers should be 3m and 5m.  Maybe you can look at the laser values (as they are measured in meters or centimeters) to set the rectangle scale...

**Comment by damodardatta** [comment]
![Screenshot from 2024-04-02 23-59-54](https://github.com/JdeRobot/RoboticsAcademy/assets/33845372/783ada7d-2dbe-4ac2-8a6d-67ba5b293427)


Hi @jmplaza, i changed the values and changed the rectangles to semicircle as i felt they would be more intuitive. Let know if this is ok?

**Comment by javizqh** [comment]
As this UI has already been updated I will close this issue.
![Screenshot from 2024-07-03 18-21-19](https://github.com/JdeRobot/RoboticsAcademy/assets/124056014/de2070dc-e6e2-4c46-af38-a23b70d0b7bc)

If you want to continue modifying this UI please open a new one
