### ISSUE TITLE
[Humble] Exercise didn't terminate correctly

### ISSUE THREAD

**Issue by pawanw17** [JdeRobot/RoboticsAcademy#2303]
While testing Rescue People exercise in Humble, the exercise loop got stuck and kept running even after exiting to menu.
![image](https://github.com/JdeRobot/RoboticsAcademy/assets/40732709/e34fc73a-9736-43d9-bc82-3dcaff4b9b56)

**Comment by pariaspe** [comment]
Hey @ango1994 , could you take a look at this? Thanks!

**Comment by ango1994** [comment]
Hi @pawanw17! Could you provide more information about this issue? I just launched the RADI 4.4.19 and executed some code to make the drone take off. After closing every process terminates correctly. How can I replicate this error?

**Comment by pawanw17** [comment]
@ango1994, Unfortunately, this is an intermittent issue and I do not have specific steps to reproduce it, I have come across this a few times on the latest RADI (4.4.19).

**Comment by pawanw17** [comment]
Hi @ango1994 , fortunately I found a way to reproduce this issue try running this code in the editor and then restart and play the exercise, this crashes the exercise

```python
from GUI import GUI
from HAL import HAL
import time

print("Hi")
time.sleep(100)


while True:
    # Enter iterative code!
    print("Hello")
```

**Comment by pawanw17** [comment]
Solved in superthin refactoring
