### ISSUE TITLE
Cannot import epylint form pylint

### ISSUE THREAD

**Issue by VlasanRobert** [JdeRobot/RoboticsAcademy#2315]
Hello 

I have an issue when i try to set up the environment i get the followingerror when i want to run the python3 manage.py runserver
ImportError: cannot import name 'epylint' from 'pylint' (/home/robiti/Documents/RoboticsAcademy/env/lib/python3.11/site-packages/pylint/__init__.py)

**Comment by pawanw17** [comment]
The issue is because epylint was removed from pylint in v3.0.0

**Comment by pawanw17** [comment]
As a workaround, uninstall pylint and instead install this older version.

`pip3 install pylint==2.17.4`

**Comment by VlasanRobert** [comment]
thank you for your help 
i still have one issue when i run the dokcer i get the following error:docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.

**Comment by jmplaza** [comment]
Take a look at this answer [https://github.com/JdeRobot/RoboticsAcademy/issues/2317#issuecomment-1807154635](https://github.com/JdeRobot/RoboticsAcademy/issues/2317#issuecomment-1807154635)
