### ISSUE TITLE
dokcer permision denied

### ISSUE THREAD

**Issue by VlasanRobert** [JdeRobot/RoboticsAcademy#2317]
Hello 

when i try to run the command for the  command for the docker i get the following error:docker: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create": dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.

**Comment by jmplaza** [comment]
Hi @VlasanRobert , 

that is a well known issue from[ docker execution itself](https://github.com/JdeRobot/RoboticsAcademy/issues/2317), not a problem with RoboticsAcademy at all. You may solve it with:` sudo chmod -x /var/run/docker.sock`
