### ISSUE TITLE
[Global Navigation] Broken showNumpy after last update

### ISSUE THREAD

**Issue by franmore-urjc** [JdeRobot/RoboticsAcademy#2322]
The PR #2320  has broken the GUI.showNumpy function in the "Global Navigation" exercise. It was working fine before by passing a single channel uint8 image, but now it does some weird things.

In the screenshot I am trying to vizualize a simple grayscale image but it shows some vertical color lines.

![image](https://github.com/JdeRobot/RoboticsAcademy/assets/148446552/d1ab307c-20ee-4054-a320-d760f1d7e671)

What kind of image format is it expecting now? Could this be updated in the documentation of the exercise?

**Comment by ReyDoran** [comment]
Closed by #2329
