### ISSUE TITLE
[Humble] Restarting the exercise automatically plays the code, while the play/pause button doesn't update

### ISSUE THREAD

**Issue by pawanw17** [JdeRobot/RoboticsAcademy#2392]
The play button is stuck if I press it again the the code will start from scratch

![image](https://github.com/JdeRobot/RoboticsAcademy/assets/40732709/b766bdf7-4aad-4ebc-8f6c-dc70b5b22225)

Should the code execution be stopped when restart is pressed?

This also leads to the widget not starting up when the exercise is restarted

**Comment by jmplaza** [comment]
Hopefully this issue will be solved with the upcoming RAM and template refactoring

**Comment by pawanw17** [comment]
Fixed with #2451
