### ISSUE TITLE
Unable to launch Exercises on M1 Mac

### ISSUE THREAD

**Issue by AryanNanda17** [JdeRobot/RoboticsAcademy#2395]
Hi, I am unable to launch exercises on my M1 Mac:-
I followed [these](https://github.com/JdeRobot/RoboticsAcademy/blob/master/docs/InstructionsForDevelopers.md) instructions for the setup of RoboticsAcademy locally.
Whenever I run the docker image and try to launch an exercise, my screen gets stuck here:-
<img width="1440" alt="Screenshot 2024-01-13 at 12 45 09 AM" src="https://github.com/JdeRobot/RoboticsAcademy/assets/125150482/c3da95e5-44b0-459a-87f1-792af058cc49">
These are the generated logs:-
```
[root][ERROR] 2024-01-13 04:36:54,432: Invalid roslaunch XML syntax: [Errno 2] No such file or directory: '/opt/jderobot/Launchers/simple_circuit_followingcam.launch.py'
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 741, in _parse_launch
    root = parse(filename).getElementsByTagName('launch')
  File "/usr/lib/python3.8/xml/dom/minidom.py", line 1959, in parse
    return expatbuilder.parse(file)
  File "/usr/lib/python3.8/xml/dom/expatbuilder.py", line 910, in parse
    with open(file, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/jderobot/Launchers/simple_circuit_followingcam.launch.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/config.py", line 461, in load_config_default
    loader.load(f, config, argv=args, verbose=verbose)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 761, in load
    launch = self._parse_launch(filename, verbose)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 743, in _parse_launch
    raise XmlParseException("Invalid roslaunch XML syntax: %s"%e)
roslaunch.xmlloader.XmlParseException: Invalid roslaunch XML syntax: [Errno 2] No such file or directory: '/opt/jderobot/Launchers/simple_circuit_followingcam.launch.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "RoboticsAcademy/src/manager/manager/manager.py", line 281, in start
    self.process_messsage(message)
  File "RoboticsAcademy/src/manager/manager/manager.py", line 245, in process_messsage
    self.trigger(message.command, data=message.data or None)
  File "/usr/local/lib/python3.8/dist-packages/transitions/core.py", line 922, in _get_trigger
    return event.trigger(model, *args, **kwargs)
```

**Comment by jmplaza** [comment]
Hi @AryanNanda17 ,

uhm... those instructions are for developer deployment of RoboticsAcademy. As regular user it is more simple:

1. Download the latest RADI (for ROS1-Noetic is 3.4.28) from [DockerHub](https://hub.docker.com/r/jderobot/robotics-academy/tags)
2. Start the RADI using: `docker run --rm -it -p 7681:7681 -p 2303:2303 -p 1905:1905 -p 8765:8765 -p 6080:6080 -p 1108:1108 -p 7163:7163 -p 7164:7164 jderobot/robotics-academy:3.4.28`
3. Open your local browser and select this URL: `http://127.0.0.1:7164/`

**Comment by AryanNanda17** [comment]
Thanks!!
I thought for contributing to RoboticsAcademy, I have to follow those instructions for setup and it kept giving me errors even after trying many different things. 
Anyways, what do you suggest from which exercise should I start?

**Comment by jmplaza** [comment]
FollowLine and Basic Vacuum Cleaner as a regular user, try to solve them and enjoy :-). For studying the underlying code Vacuum Cleaner is the best one.
