### ISSUE TITLE
[New Commers Issue] Forum doesn't open on a new tab

### ISSUE THREAD

**Issue by pawanw17** [JdeRobot/RoboticsAcademy#2406]
The forum should open on a new tab.

![image](https://github.com/JdeRobot/RoboticsAcademy/assets/40732709/2c0bd330-9e9e-4085-a2c1-09e801ed6143)

**Comment by devaggarwal-1** [comment]
Could you elaborate a bit more?

**Comment by Navneet7716** [comment]
hey @pawanw17 can I pick this up?

**Comment by jmplaza** [comment]
Sure @Navneet7716 . We don't follow any booking for solving the issues. Feel free to work on your solution and submit your PR which solves it. It will be reviewed by a committer and in positive case merged into the master branch ASAP.

**Comment by Navneet7716** [comment]
Hey @jmplaza added a pr hopefully this is what is required in the change.

**Comment by pawanw17** [comment]
closed by #2408

**Comment by pawanw17** [comment]
Reopening this because of superthin refactoring

**Comment by CDAM2020** [comment]
I've just made and merged the pr #2523 fixing this

**Comment by jmplaza** [comment]
Fixed in #2523
