### ISSUE TITLE
Proper ROS version retrieval for developer RA

### ISSUE THREAD

**Issue by OscarMrZ** [JdeRobot/RoboticsAcademy#2407]
Currently, when the RA django backend wants to load an exercise, it queries the local env variable ROS_VERSION. This is the intended behavior when it is running inside the RADI (which has the proper variables set up). However, in "developer mode", that is, running the django backend locally, it queries the developer ros installation, giving problems when there is a version mismatch with the RADI. 

I think the easiest solution may be to include the instructions to change the environment variable in the developer documentation. Simply:

```bash
export ROS_VERSION=2 # For 4.x radi
export ROS_VERSION=1 # For 3.x radi
```

**Comment by javizqh** [comment]
This is solved in the current version
