### ISSUE TITLE
[Thin Templates Noetic] Remove duplicate frequency setting code in exercises and test them

### ISSUE THREAD

**Issue by pawanw17** [JdeRobot/RoboticsAcademy#2417]

**Comment by razelos** [comment]
Hello, I'm interested in picking up this issue. Could you provide some further specification about which frequency setting code you're referring to? Thanks

**Comment by pawanw17** [comment]
Hi @razelos Unfortunately the Noetic counterpart of Robotics Academy is not in active development and this issue will be closed. Feel free to take up any of the more recent issues dealing with ROS 2 Humble.

**Comment by razelos** [comment]
Okay thanks
