### ISSUE TITLE
[New Manager] Migrate all exercises to new 4-step RAM and superthin templates

### ISSUE THREAD

**Issue by OscarMrZ** [JdeRobot/RoboticsAcademy#2418]
# ROS1 Noetic
- [x] ~Follow line   (deprecated as it is available in ROS2 Humble)~
- [x] ~Basic Vacuum Cleaner  (deprecated as it is available in ROS2 Humble)~
- [x] ~Autoparking   (deprecated as it is available in ROS2 Humble)~
- [x] ~Localized Vacuum Cleaner   (deprecated as it is available in ROS2 Humble)~
- [x] ~Global Navigation  (deprecated as it is available in ROS2 Humble)~
- [x] ~Obstacle Avoidance  (deprecated as it is available in ROS2 Humble)~
- [ ] ~Rescue people   (deprecated as it is available in ROS2 Humble)~
- [x] ~3D reconstruction  (deprecated as it is available in ROS2 Humble)~
- [ ] Power tower inspection
- [ ] Follow road
- [ ] Visual lander
- [ ] Labyrinth escape
- [ ] Position control
- [ ] Drone hangar
- [ ] Drone gymkhana
- [ ] Montecarlo visual loc

# ROS2 Humble
- [x] **Follow line**   (Migrated to superthin but has an issue with widgets (see #2464) )
- [x] Global Navigation (@javizqh )
- [x] Obstacle Avoidance (@javizqh )
- [x] Basic vacuum cleaner  (@OscarMrZ )
- [x] Autoparking   (@pawanw17 )
- [x] Follow person  (@OscarMrZ )
- [x] Localized vacuum cleaner  (@OscarMrZ )
- [x] **Rescue people**
- [x] Amazon Warehouse (widget not resetting (see #2476) @pawanw17 )
- [x] Montecarlo laser loc 
- [x] 3D reconstruction (@pawanw17 )

**Comment by pawanw17** [comment]
Hi @Surajpatra700, Unfortunately this is more of an intermediate-level issue, I suggest you check out this answer which tells how to get started with RoboticsAcademy 
https://github.com/orgs/JdeRobot/discussions/233#discussioncomment-7983227

Feel free to play around with the application and file/solve any bugs you see

**Comment by Tanishq30052002** [comment]
Hi @pawanw17 ,
I would like to work on the migration of a project, could you please assist with where to start if still there is work needed?
Thanks

**Comment by jmplaza** [comment]
The 11 core exercises have been already updated and migrated to ROS2 Humble and SuperThin templates. 

For the remaining exercises, there is a new issue https://github.com/JdeRobot/RoboticsAcademy/issues/2607
