### ISSUE TITLE
[New manager] Frontend support for new manager world reload mechanism

### ISSUE THREAD

**Issue by OscarMrZ** [JdeRobot/RoboticsAcademy#2419]
Currently, the new startup sequence messages are only sent in the first world launch and not in the reload. This should be changed in [the world selector](https://github.com/JdeRobot/RoboticsAcademy/blob/master/react_frontend/src/components/visualizers/WorldSelector.js).

**Comment by OscarMrZ** [comment]
Also, the RAM will have separate terminate functions for each level, so the frontend should be changed to send the appropiate new messages.

**Comment by Surajpatra700** [comment]
Hey @OscarMrZ can you please tell me, what should i actually need to do right now.

**Comment by OscarMrZ** [comment]
This was fixed at #2420. @Surajpatra700, we are currently undergoing a very intense manager refactorization. Please feel to test it (branch superthin-dev) and report any bugs or improvements you find.
