### ISSUE TITLE
Review the installation Instructions for Developers

### ISSUE THREAD

**Issue by AryanNanda17** [JdeRobot/RoboticsAcademy#2442]
Since many users are facing difficulties in doing developer setup of RoboticsAcademy, there is a need to review and update the [Instructions for developers](https://github.com/JdeRobot/RoboticsAcademy/blob/master/docs/InstructionsForDevelopers.md).
@jmplaza , could you please suggest any changes and assign me on this issue. 
Thanks

**Comment by OscarMrZ** [comment]
Hello @AryanNanda17. We are in the middle of intense refactoring, so the docs are changing quite a lot. If you'd like, please test the new docker compose installation and suggest any changes/issues you may find.

**Comment by Apoorvgarg-creator** [comment]
@AryanNanda17, Using **Conda** to create Environment seems a nice update in the documentation.

**Comment by javizqh** [comment]
Updating the naming scheme of RADI to RoboticsBackend has been done in this issue #2620

**Comment by javizqh** [comment]
Maybe we could add how to create a GUI and a HAL using gui_interfaces and hal_interfaces
