### ISSUE TITLE
 Functionality issues in modified develop_academy.sh script

### ISSUE THREAD

**Issue by vaishnavimulik25** [JdeRobot/RoboticsAcademy#2465]
![error](https://github.com/JdeRobot/RoboticsAcademy/assets/126563312/c22c48d0-e1bd-41ad-9e3f-9e3dce99669e)
I have followed the latest documentation and used the latest script for installation. Since I was getting this issue I tried manually running commands in develop.sh script. I found error during npm install.

**Comment by vaishnavimulik25** [comment]
[Modified develop_academy.sh](https://github.com/JdeRobot/RoboticsAcademy/pull/2466)

**Comment by OscarMrZ** [comment]
Hi @vaishnavimulik25, thanks for your time! Please describe your issue in more detail, why are you using npm? RA uses yarn as the package manager, and should always be used (as it is in the script). Do you also have errors with yarn?

Regarding

**Comment by vaishnavimulik25** [comment]
Yes I had errors with yarn previously but after using [updated develop_academy.sh](https://github.com/JdeRobot/RoboticsAcademy/commit/cfa60b532e5fbb7e6d4a0245dd711925ffc91b79) I didn't had error.

**Comment by OscarMrZ** [comment]
Outdated due to big changes in main branch. Please feel free to reopen if you think we are missing something!
