### ISSUE TITLE
Error in adding new exercise section 

### ISSUE THREAD

**Issue by vaishnavimulik25** [JdeRobot/RoboticsAcademy#2471]
I was following the Adding new exercise section in  [InstructionsForDevelopers](https://github.com/JdeRobot/RoboticsAcademy/blob/master/docs/InstructionsForDevelopers.md) While running "python3 manage.py runserver 0.0.0.0:7164", I got this error. 
![Screenshot from 2024-03-30 19-01-08](https://github.com/JdeRobot/RoboticsAcademy/assets/126563312/ea5ea90c-54a5-4ad2-9217-d96f48e463ca)

I checked the [requirements.txt](https://github.com/JdeRobot/RoboticsAcademy/blob/master/docs/requirements.txt) and pylint version was not specified. I have worked on this issue. I figured out pylint==2.17.4 version works for it.

**Comment by pawanw17** [comment]
Hi @vaishnavimulik25 Can you make a PR for it?

**Comment by vaishnavimulik25** [comment]
Hi @pawanw17 Yes I will make PR immediately.

**Comment by pawanw17** [comment]
fixed by #2479
