### ISSUE TITLE
Cannot run RoboticsAcademy locally

### ISSUE THREAD

**Issue by Henrysssong** [JdeRobot/RoboticsAcademy#2481]
I just forked and cloned the repo and tried curl -s https://raw.githubusercontent.com/JdeRobot/RoboticsAcademy/master/scripts/run_academy.sh | sudo bash as instructed in the READEME file, 
![image](https://github.com/JdeRobot/RoboticsAcademy/assets/104670460/c31f6f10-44e8-4dc7-8285-6b7514c6326f)

but there's no docker-compose.yml file, so I got Non-string key at top level: 404.

**Comment by javizqh** [comment]
Now it seems to be working, so I will close this issue
