### ISSUE TITLE
[Rescue people] Drone starts flying after restart

### ISSUE THREAD

**Issue by agonzc34** [JdeRobot/RoboticsAcademy#2484]
In the exercice Rescue people when I click on the restart button, it resets the world models, but it outputs the next log in the docker terminal and it does not allow me to run my code.
Working on 4.5.7.BETA.

12:48:33 [MainThread  ] [ERROR] (my_app_logger)  [Errno 32] Broken pipe
Traceback (most recent call last):
  File "//RoboticsAcademy/src/manager/manager/manager.py", line 466, in start
    self.process_messsage(message)
  File "//RoboticsAcademy/src/manager/manager/manager.py", line 364, in process_messsage
    self.gui_server.send(message.data)
  File "/RoboticsAcademy/src/manager/libs/applications/compatibility/server.py", line 39, in send
    self.server.send_message(self.current_client, data)
  File "/usr/local/lib/python3.10/dist-packages/websocket_server/websocket_server.py", line 78, in send_message
    self._unicast(client, msg)
  File "/usr/local/lib/python3.10/dist-packages/websocket_server/websocket_server.py", line 195, in _unicast
    receiver_client['handler'].send_message(msg)
  File "/usr/local/lib/python3.10/dist-packages/websocket_server/websocket_server.py", line 344, in send_message
    self.send_text(message)
  File "/usr/local/lib/python3.10/dist-packages/websocket_server/websocket_server.py", line 413, in send_text
    self.request.send(header + payload)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by OscarMrZ** [comment]
Does this still happen with the last RADI?

**Comment by pawanw17** [comment]
Can confirm that the error exists in latest humble-devel,but even after the error I am able to run the code as expected

**Comment by agonzc34** [comment]
I have tested on 3.4.30 and on 4.5.9 docker images.
On 3.4.30 the error log doesn't show and it allows me to restart the exercise, but when I restart the simulation, the drone starts flying randomly.
On 4.5.9 it doesn't even start, it logs this:
![image](https://github.com/JdeRobot/RoboticsAcademy/assets/55236157/11eee85a-e00a-41ea-96b2-b7d98d4ae076)

**Comment by pawanw17** [comment]
Hi @agonzc34 the 'hal_interfaces' issue in 4.5.9 is fixed in master and you will be able to run the exercise without issue in the upcoming 4.5.10

regarding 3.4.30, we are aware of that issue but ROS1 RADI is no more in active development

**Comment by jmplaza** [comment]
Hi @agonzc34,
 
RADI 4.5.10 has been released. Drone-rescue-people exercise is working fine again. Could you please check it?

**Comment by javizqh** [comment]
With 4.6.1 there is no error when resetting but the drone starts flying even if the code is empty after resetting the exercise.

**Comment by javizqh** [comment]
@pariaspe Do you know what could be making the drone not reset itself properly when clicking the reset button, but working properly when changing to another exercise and the starting this exercise again?

**Comment by pariaspe** [comment]
> @pariaspe Do you know what could be making the drone not reset itself properly when clicking the reset button, but working properly when changing to another exercise and the starting this exercise again?

My guess is that PX4 (the autopilot simulated within gazebo) is not well reset

**Comment by pawanw17** [comment]
@javizqh @pariaspe I am certain that this didn't used to happen.

EDIT: I tested old version of the exercise in 4.4.15 and the issue indeed occurs there as well—something left in testing.
We should have a better way to close exercises involving drones

**Comment by pawanw17** [comment]
I am closing this issue and opening another one.
