### ISSUE TITLE
Exercise loaded message is error-themed even when successful

### ISSUE THREAD

**Issue by Apolo151** [JdeRobot/RoboticsAcademy#2492]
The message after loading the exercise is error-themed even when the exercise is loaded successfully, which is somewhat confusing.

![1](https://github.com/JdeRobot/RoboticsAcademy/assets/64263339/0b95c44e-4da8-484c-a962-5bc05a2066a9)
![2](https://github.com/JdeRobot/RoboticsAcademy/assets/64263339/b6475164-5ab9-4e32-95d4-7d7c296284d3)

**Comment by pawanw17** [comment]
@Apolo151 Feel free to change it and make a PR, also work on RADI 4.5.9 as 3.x are not in active development

**Comment by espilya** [comment]
Fixed in #2612
Fix will be available in future updates.
