### ISSUE TITLE
Update exercises docs with docker compose launching

### ISSUE THREAD

**Issue by Syekeon** [JdeRobot/RoboticsAcademy#2494]
It could be a good idea adding the docker compose launching in those exercises already working with the last versions.

**Comment by Syekeon** [comment]
Also I could be a good idea changing the docker launch without the ports that aren't using in the last versions (or adding a second launch in docs depending on the RADI version)

**Comment by jmplaza** [comment]
AFAIK only the mapping of 4 ports is required now. For instance:
`docker run --rm -it -p 7164:7164 -p 6080:6080 -p 1108:1108 -p 7163:7163 jderobot/robotics-academy:4.5.9`

- 7163 for connection between the exercise web page and the RAM
- 6080 vnc websocket for Gazebo viewer
- 1108 vnc websocket for console viewer
- 7164 for local webserver

**Comment by pawanw17** [comment]
Hi @Syekeon In amazon warehouse exercise I have reverted to lift() and putdown()... so let's keep it that way... you may have to update the PR _pages/exercises/MobileRobots/amazon_warehouse.md

**Comment by Syekeon** [comment]
@pawanw17 Done it!
