### ISSUE TITLE
Move interfaces to Robotics Infrastructure repo (hal_interfaces)

### ISSUE THREAD

**Issue by pawanw17** [JdeRobot/RoboticsAcademy#2506]
- [x] Global Navigation
- [x] Obstacle Avoidance
- [x] Basic vacuum cleaner
- [x] #2562
- [x] #2563
- [x] Follow person
- [x] Localized vacuum cleaner
- [x] Rescue people
- [x] #2566
- [x] #2564
- [x] #2572

**Comment by jmplaza** [comment]
`hal_interfaces` is something very related to RoboticsAcademy and not to other general robotics applications. It is part of the templates of the RA exercises. What about putting `hal_interfaces` in a directory named `common` (or something similar) in the RoboticsAcademy repo itself?

**Comment by pawanw17** [comment]
Yes, that sounds better... we can also move console.py and a genericGUI.py there and have the GUI.py in the exercises be a child class of genericGUI.py

Some of the hal_interfaces have already moved to RI though, https://github.com/JdeRobot/RoboticsInfrastructure/tree/humble-devel/hal_interfaces/hal_interfaces

**Comment by pawanw17** [comment]
Hi @jmplaza, On digging further I found that @OscarMrZ has made ros nodes out of the hal interfaces which gets compiled with other ros2 nodes, custom robots etc, I think that is an elegant way of doing things... what do you think?

**Comment by javizqh** [comment]
- [X ]  Global Navigation
- [X ]  Obstacle Avoidance
- [X ]  Basic vacuum cleaner
- [ ]   Follow line
- [ ]   Autoparking
- [X ]   Follow person
- [X ]   Localized vacuum cleaner
- [X ]   Rescue people
- [ ]   Amazon Warehouse
- [ ]   Montecarlo laser loc
- [ ]   3D reconstruction
