### ISSUE TITLE
[Vacuum Cleaner] Map not updating

### ISSUE THREAD

**Issue by javizqh** [JdeRobot/RoboticsAcademy#2537]
This happens for the basic one and the localized one.

https://github.com/JdeRobot/RoboticsAcademy/assets/124056014/321f9690-2e20-46ac-9a77-a8f413145734

**Comment by javizqh** [comment]
Can you if it works for you @pawanw17 ?

**Comment by pawanw17** [comment]
@javizqh seems to be working fine

**Comment by pawanw17** [comment]
It seems I tested the loc vacuum cleaner, the map updates there. But not in basic vacuum cleaner.

**Comment by pawanw17** [comment]
Fixed in #2600
