### ISSUE TITLE
[Obstacle avoidance] Not receiving images from camera

### ISSUE THREAD

**Issue by javizqh** [JdeRobot/RoboticsAcademy#2544]
It does not receive the images from the camera topic and it gets stuck infinitely.
It happens randomly so more testing is needed to find why it happens

**Comment by javizqh** [comment]
It happens randomly

**Comment by javizqh** [comment]
If someone can test it a couple of times it would be helpful.
I only manage to experience this behavior once, the first time I launched the docker. The rest of the times it would work perfectly

**Comment by jmplaza** [comment]
Maybe in this exercise we could even remove the camera, as it is not required. The solution for this challenge only requires laser and position to work. The onboard vision definitely is nice and cool, but it takes a significant computational cost... and so reduces the Gazebo RTF. 

What do you think?  @pawanw17 @javizqh

**Comment by javizqh** [comment]
I think we could remove it and just make the camera follow the car in Gazebo
It will be the same but just once

**Comment by javizqh** [comment]
Here is a video of what the change could be

https://github.com/JdeRobot/RoboticsAcademy/assets/124056014/a01fc85c-5c1f-4275-b12b-43ac0410ab33


https://github.com/JdeRobot/RoboticsAcademy/assets/124056014/9af4ad56-a188-48a0-8ea6-76ce2029870c

**Comment by javizqh** [comment]
Or if we want the proportions to remain to not widen it, it could look like this:
![Screenshot from 2024-06-03 12-48-00](https://github.com/JdeRobot/RoboticsAcademy/assets/124056014/5588d283-fb71-44ee-9db4-e01ae0111a35)

**Comment by jmplaza** [comment]
Cool. I would set the background color in the upper image to gray, more similar to the pavement. That way the only blue things are the laser readings, both in the upper image and in the Gazebo Viewer

**Comment by javizqh** [comment]
So something like this would be the new UI:

**Comment by javizqh** [comment]
![Screenshot from 2024-06-03 13-15-57](https://github.com/JdeRobot/RoboticsAcademy/assets/124056014/ba1e2e70-f01e-46c1-a52a-75438ee0bf9f)

**Comment by pawanw17** [comment]
@jmplaza Does this look alright or we should spread the widget as @javizqh had suggested?
![image](https://github.com/JdeRobot/RoboticsAcademy/assets/40732709/5def27bd-0af4-4416-bd68-7fdd9a60441e)
am not a big fan of yellow

**Comment by jmplaza** [comment]
:-) let's spread the widget, and let the orange be only in the top horizontal bar

**Comment by javizqh** [comment]
Which one of the 3 is better:
![Screenshot from 2024-06-04 17-22-17](https://github.com/JdeRobot/RoboticsAcademy/assets/124056014/599bdd76-20ee-4c87-8900-02f725847e9c)
![Screenshot from 2024-06-04 17-21-07](https://github.com/JdeRobot/RoboticsAcademy/assets/124056014/fcccbcfa-5e88-4585-8a31-cb5e97eecc82)
![Screenshot from 2024-06-04 17-19-55](https://github.com/JdeRobot/RoboticsAcademy/assets/124056014/d235fa12-f7ac-4911-8a13-1282f84bef46)

**Comment by jmplaza** [comment]
The first one, from my point of view

**Comment by jmplaza** [comment]
Instead of 3.5m, maybe we could draw it at 5m, by the way.

**Comment by javizqh** [comment]
The max laser distance is 6.8 meters, so maybe with a 5m box it goes outside of the border of the widget

**Comment by pawanw17** [comment]
@javizqh Can you please check and update? if 5m box goes out?

**Comment by javizqh** [comment]
It fits perfectly

![Screenshot from 2024-06-04 18-10-42](https://github.com/JdeRobot/RoboticsAcademy/assets/124056014/48571ff0-e3e1-4b33-8e04-30f0c9d745fb)
