### ISSUE TITLE
Optimized exercises

### ISSUE THREAD

**Issue by javizqh** [JdeRobot/RoboticsAcademy#2570]
- [X] Global Navigation
- [X] Obstacle Avoidance
- [x] Basic vacuum cleaner
- [X] Follow Line
- [x] Autoparking
- [x] #2579
- [x]  Localized vacuum cleaner
- [x]  Rescue people
- [x] Amazon Warehouse
- [x]  Montecarlo laser loc
- [x] 3D reconstruction

**Comment by javizqh** [comment]
Same as https://github.com/JdeRobot/RoboticsInfrastructure/issues/395

**Comment by javizqh** [comment]
The performance achieved with this update for my setup and the RADI 4.6.0 can be seen in the following images:

![Screenshot from 2024-06-29 19-40-11](https://github.com/JdeRobot/RoboticsAcademy/assets/124056014/e3a9dca0-0c92-43d1-aca1-4e34d0d5a073)
![Screenshot from 2024-06-29 19-39-58](https://github.com/JdeRobot/RoboticsAcademy/assets/124056014/0fe1217f-c5cf-48b9-a2af-3efaf6618266)

The only thing to test further is the autoparking exercise and fix the visual glitches

**Comment by pawanw17** [comment]
Closed with v5.2.3 release.
