### ISSUE TITLE
[3D reconstruction] Does not work on Chrome or Chromium based browsers 

### ISSUE THREAD

**Issue by javizqh** [JdeRobot/RoboticsAcademy#2583]
The 3D canvas that appears on Firefox does not appear on Chrome or Chromium based browsers causing the exercise to crash when you execute GUI.ShowNewPoints() a couple of times.

Firefox
![Screenshot from 2024-06-20 13-27-28](https://github.com/JdeRobot/RoboticsAcademy/assets/124056014/09923e70-66a8-4532-a572-3ab04063d504)

Chromium or Chrome
![Screenshot from 2024-06-20 13-27-12](https://github.com/JdeRobot/RoboticsAcademy/assets/124056014/6383d620-0682-4f6f-9164-328c536777c9)

**Comment by javizqh** [comment]
In Chromium the width of the canvas is set to 0, while in Firefox it has an actual width.

Same happens with the images from the exercise. In Firefox they fit within the UI, but in Chromium the images appear bigger than they should, not displaying the image properly

**Comment by javizqh** [comment]
After the PR the issue that remains is that the camera images are not displayed properly on chrome:

# Chrome:

![Screenshot from 2024-06-20 14-08-09](https://github.com/JdeRobot/RoboticsAcademy/assets/124056014/be169939-190e-4845-abef-167dec5a342c)
![Screenshot from 2024-06-20 14-07-59](https://github.com/JdeRobot/RoboticsAcademy/assets/124056014/805728f6-b906-4868-88c0-48e423f26734)

# Firefox:

![Screenshot from 2024-06-20 14-09-42](https://github.com/JdeRobot/RoboticsAcademy/assets/124056014/a02e708e-b989-4e72-9d36-8c268c5139cf)

**Comment by Apoorvgarg-creator** [comment]
@javizqh Are you working on this issue ? I see you have raised one PR and still some problem is occurring on this.

If possible, we can work together on this issue.

**Comment by javizqh** [comment]
I made a quick fix in order to have the exercise working at least.

**Comment by pawanw17** [comment]
Unfortunately, I never faced the crash issue, I used Chrome on Ubuntu 20.04 while testing

**Comment by Apoorvgarg-creator** [comment]
Hi @javizqh For me It is running perfectly fine in Chrome

**Comment by javizqh** [comment]
Tell @pawanw17 to test it, if It works for him we can close this issue

**Comment by pawanw17** [comment]
Looks fine to me:
![image](https://github.com/JdeRobot/RoboticsAcademy/assets/40732709/79a27648-67a9-4730-bb54-8c17fb7bd37c)
