### ISSUE TITLE
Adding information of the original reference system in amazon warehouse

### ISSUE THREAD

**Issue by alcabmo** [JdeRobot/RoboticsAcademy#2585]
We should add somewhere in the text an image or a text pointing how the HAL functions understand the 2D work plane

**Comment by alcabmo** [comment]
I tried to solve it in my branch https://github.com/alcabmo/RoboticsAcademy/tree/patch-1 , hope it helps

**Comment by alcabmo** [comment]
I tried solving it in my own repo https://github.com/alcabmo/RoboticsAcademy/tree/patch-1, hope it helps. I only add and image and changed the of amazon_warehouse.md

**Comment by lu164** [comment]
Hi @alcabmo, maybe it is more appropriate to put that information in the Robot API section?

**Comment by lu164** [comment]
I made the modification mentioned and the issue is fixed in #2589

**Comment by jmplaza** [comment]
Merged! good job @alcabmo @lu164
