### ISSUE TITLE
Update Robotics Academy Image in compose_cfg

### ISSUE THREAD

**Issue by Apoorvgarg-creator** [JdeRobot/RoboticsAcademy#2594]
Currently, The latest development version of  ~~RAM~~ RADI is **4.5.13**

But In **Yaml** files present inside **compose_cfg** is pointing to **4.5.9**

**Comment by jmplaza** [comment]
??According to the [RAM repo](https://github.com/JdeRobot/RoboticsApplicationManager/releases), 5.2.0 is the last packaged release of RAM. 

Those numbers you mention seem RADI release numbers...

**Comment by Apoorvgarg-creator** [comment]
> ??According to the [RAM repo](https://github.com/JdeRobot/RoboticsApplicationManager/releases), 5.2.0 is the last packaged release of RAM.
> 
> Those numbers you mention seem RADI release numbers...

Yes, Accidently I typed RAM. Apologies for the mistake.
I meant RADI
