### ISSUE TITLE
Switch all GUI's from two class to only one

### ISSUE THREAD

**Issue by javizqh** [JdeRobot/RoboticsAcademy#2601]
For now we are using the old 2 class approach and to be able to switch to one it is needed to solve the UI rendering issues with it

**Comment by espilya** [comment]
Can I get more context of this issue? 
Are `ThreadGUI` and `GUI` the two classes that should be merged?

**Comment by javizqh** [comment]
Yes, you can use as a example the basic vacuum cleaner done by Óscar

**Comment by javizqh** [comment]
@espilya have you make any progress with this issue?
If not @dduro2020 and @javizqh will start working on it.

**Comment by espilya** [comment]
@javizqh I've made almost no progress on this. Continue as I see it will be easier for you to complete this issue.

**Comment by javizqh** [comment]
Thanks for trying
