### ISSUE TITLE
Maps’ static images in certain exercises (Amazon Warehouse, …) do not load in Unibotics when using Robotics Academy as a submodule

### ISSUE THREAD

**Issue by mariabusto** [JdeRobot/RoboticsAcademy#2608]
Maps’ static images in certain exercises (Amazon Warehouse, Global Navigation, Montecarlo Laser Loc, Localized Vacuum Cleaner, Vacuum Cleaner) do not load correctly when using Unibotics due to the adaptations applied in order to use Robotics Academy as a submodule of Unibotics, as well as the widgets’ refactorization.

**Comment by CDAM2020** [comment]
It's been modified with Django settings on Unibotics.
