### ISSUE TITLE
Incorrect line error in console

### ISSUE THREAD

**Issue by dduro2020** [JdeRobot/RoboticsAcademy#2655]
I think it would be interesting to see how the console can return the actual error line, it always has a margin of failure and when your program has many lines you can go crazy looking for it.

![imagen](https://github.com/user-attachments/assets/8fa13764-0879-432a-ad9d-93912215d496)

**Comment by pawanw17** [comment]
That's True, the issue is, the user code is passed to the RAM where some more lines of code are added for setting the frequency... which causes this margin of failure...

**Comment by javizqh** [comment]
This can be closed with the merge of https://github.com/JdeRobot/RoboticsApplicationManager/pull/141
