### ISSUE TITLE
Broken Pipe error when reloading the application while it is running in Robotics Academy exercises

### ISSUE THREAD

**Issue by mariabusto** [JdeRobot/RoboticsAcademy#2666]
The following Broken Pipe error appears in the Robotics Backend when the application is reloaded while it is running in the Robotics Academy exercises: 

![Broken Pipe Error - Robotics Academy](https://github.com/user-attachments/assets/2ac65b53-b326-4b94-9602-0f3bf828c45b)

It seems that this error could be related to the number of ports used in the docker-compose.yaml file when deploying Robotics Academy.

**Comment by jmplaza** [comment]
Moved to RAM repo https://github.com/JdeRobot/RoboticsApplicationManager/issues/161
