### ISSUE TITLE
Fix auto-delete for showAlert message

### ISSUE THREAD

**Issue by espilya** [JdeRobot/RoboticsAcademy#2673]
After the timeout, no more new messages will be displayed.

**Comment by javizqh** [comment]
How can this issue be reproduced?

**Comment by espilya** [comment]
> How can this issue be reproduced?

@javizqh Launch an exercise, after the timeout (5 secs) of the first popup is ended and the popup is closed, try to launch a pylint error. 
There should be a popup message with the pylint error. But it only appears if you launch the pylint error during the first 5 secs. 

So after the timeout no more popups are shown.
