### ISSUE TITLE
Console debugging flow not working properly in Rescue People

### ISSUE THREAD

**Issue by mariabusto** [JdeRobot/RoboticsAcademy#2684]
The debugging flow via the user console does not work correctly in Robotics Academy Rescue People exercise. In particular, debugging information is not being displayed in the console in the case of a syntax or a dependency error, although it is displayed in the browser’s developer console and in the Robotics Backend. 

![Console Debugging Error - Rescue People](https://github.com/user-attachments/assets/7065c7d6-4acd-4022-a24c-6296bec247b3)

This bug may be related to the launcher used by RAM, specific to this exercise and the ones with drones. Therefore, the console debugging flow for this type of exercises needs to be fixed.

**Comment by espilya** [comment]
Belongs to RAM repo (https://github.com/JdeRobot/RoboticsApplicationManager/issues/158).
