### ISSUE TITLE
Change exercises frontent from Canvas to css and html

### ISSUE THREAD

**Issue by javizqh** [JdeRobot/RoboticsAcademy#2748]
Change how the feontend for each exercises work, instead of drawing inside a Canvas use CSS and html to display the image or components

This will make the frontend look crispier and also replace PNG with svg

Exercises:

- [x]  Vacuum normal
- [x] Vacuum Localized
- [x] Montecarlo Vacuum
- [X] Follow Line
- [x] Obstacle Avoidance: IMPORTANT
- [x] Amazon Warehouse
- [x] Follow Person
- [x] Global Navigation
- [x] Autoparking
- [x] Rescue people: IMPORTANT

**Comment by devxspectre** [comment]
hey @javizqh can you assign me this task

**Comment by javizqh** [comment]
I am working in the vacuums, you may take any other.

Please create the PR for each exercise separately.
