### ISSUE TITLE
Make GPU selection process transparent to users

### ISSUE THREAD

**Issue by dpascualhe** [JdeRobot/RoboticsAcademy#2751]
As of now, we have different instructions and `docker run` command variants for different GPU architectures and OS. In order to make things easier for users, we should be able to automatically detect available GPUs and set the required environment variables accordingly. We should prioritize NVIDIA architectures, and still allow users to override the automatic selection process.

**Comment by javizqh** [comment]
That would be ideal, but some users that have Nvidia have problems installing the necessary packages. Also I'm transfering this issue to RoboticsAcademy

**Comment by dduro2020** [comment]
We could create a small script that allows the user to decide which configuration they want to use, by simply triggering it with a flag or even asking the user directly and letting them choose their configuration.
I found something to search nvidia available gpus:
```bash
$ nvidia-smi --query-gpu=name --format=csv,noheader
NVIDIA GeForce RTX 3050 Ti Laptop GPU
```

**Comment by dpascualhe** [comment]
hi! I created the issue in RoboticsInfrastructure originally as it is the repo that contains scripts such as the entrypoint and so on. Let me know if that is the right place to host them. I've opened this PR (as draft) with the scripts I've created for: (1) selecting gpu automatically and (2) benchmarking available gpus. I just wanted to push what I have so that no work is done twice, but I'll add more details and instructions later today and let you know :hugs: 

https://github.com/JdeRobot/RoboticsInfrastructure/pull/433

**Comment by javizqh** [comment]
The scripts in the RoboticsInfrastructure are outdated, and also the scripts related to the launch of the RADI are hosted in the scripts folder inside RoboticsAcademy.

So if you can, please move the Draft to RoboticsAcademy

**Comment by dpascualhe** [comment]
ok! I'll do it, but I'm a bit confused. According to the Dockerfile, all of the scripts used within the container, including the `entrypoint.sh` are still copied from RoboticsInfrastructure:
https://github.com/JdeRobot/RoboticsAcademy/blob/92e3cafc42789a966267a2928b7fdfd40f59041a/scripts/RADI/Dockerfile.mini_humble#L22

**Comment by javizqh** [comment]
We are in the process of moving some of them, and also those scripts were meant to be executed inside the docker and I suppose the ones you added are meant to be executed outside

**Comment by dpascualhe** [comment]
I've added extra details in the PR https://github.com/JdeRobot/RoboticsAcademy/pull/2754 , both of them are meant to be executed inside the container. `check_gpu.sh` is a benchmarking utility meant to be used by developers, while `set_dri_name.sh` sets the environment variable required for GPU acceleration (`DRI_NAME`) and is meant to be called as part of the entrypoint (after merging this, an update in the entrypoint would be required).

**Comment by javizqh** [comment]
Ok I will test it during the next days
