### ISSUE TITLE
Marker-based visual localization

### ISSUE THREAD

**Issue by dduro2020** [JdeRobot/RoboticsAcademy#2758]

**Comment by aastha51551** [comment]
Hi! 
Can you elaborate on the issue?

**Comment by dduro2020** [comment]
I am currently working on creating a new exercise in gazebo harmonic, this is the issue for it. This is the branch I'm working on: https://github.com/JdeRobot/RoboticsAcademy/tree/marker_visual_loc

You can also see it on the bottom right side where it says 'Development’.

**Comment by tejasps28** [comment]
Is this issue still open?
I would like to contribute to this.

**Comment by javizqh** [comment]
This issue is not open anymore. We are just finishing a couple of thing before merging
