### ISSUE TITLE
[MonteCarlo Laser Loc] the map2world and worl2map functions need good values

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#2760]
The world is exactly the same as in Localized vacuum cleaner

**Comment by javizqh** [comment]
This is for the docs, isn't it?

**Comment by jmplaza** [comment]
Nope, it is for the code. In this exercise we should provide the right functions for coordinate transformations, as the focus of the exercise is on the MonteCarlo localization algorithm itself. I mean map2world and world2map should be provided to the users and be ready to use.

**Comment by javizqh** [comment]
I already saw it. I will upload the fix later today
