### ISSUE TITLE
Change Vacuum House Map to 1012x1012

### ISSUE THREAD

**Issue by javizqh** [JdeRobot/RoboticsAcademy#2765]
Change Vacuum House Map to 1012x1012 instead of 1013x1013

**Comment by javizqh** [comment]
This will be done at the end of the mont

**Comment by ghost** [comment]
Hey, I just saw that the [map for the Monte Carlo Laser Loc](https://github.com/JdeRobot/RoboticsAcademy/blob/humble-devel/exercises/static/exercises/montecarlo_laser_loc/resources/images/mapgrannyannie.png) exercise was not updated, and it's still with a size of 1013x1012.

Is there a reason to leave this map out of the merge? The docs in gh-pages say the image is 1012x1012, but the file was not updated.

**Comment by javizqh** [comment]
I just fixed it. I thought I have changed it but it seems I did not
