### ISSUE TITLE
A directory to put the installation recipes is needed

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#278]
Both for installation of general infrastructure like ROS, OpenCV or Gazebo, and for installation of particular drivers required in the exercises like MoveIt!, MavROS, etc.

**Comment by jmvega** [comment]
A new PR has been created to solve this issue: https://github.com/JdeRobot/RoboticsAcademy/pull/283

**Comment by jmplaza** [comment]
fixed in #283
