### ISSUE TITLE
[User docs] MonteCarlo Laser Localization webpage is missing

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#2810]
it should be similar to the [MonteCarlo Visual Localization webpage](http://jderobot.github.io/RoboticsAcademy/exercises/ComputerVision/montecarlo_visual_loc). And MonteCarlo visual loc webpage should be in light red, as it is currently not available, just under construction.

**Comment by javizqh** [comment]
I already fixed it. Make sure to refresh the browser cache
