### ISSUE TITLE
[Global Navigation] Question about map image having gray borders

### ISSUE THREAD

**Issue by ghost** [JdeRobot/RoboticsAcademy#2816]
In the Global Navigation exercise, the image we get from the map represents the free space as white (value 255) and the obstacles/buildings as black (value 0).

However, the borders of the mage (the first/last row/column) are not white or black, but have some random gray values between 10-40.
Is there a reason for these pixels? I am not sure if this is a bug or if it was intentional, and if some code assumes the image is binary (free / obstacle), it may run into trouble.

Thanks in advance.

**Comment by ghost** [comment]
More information: It seems the gray pixels are not only at the image borders, but everywhere:

![image](https://github.com/user-attachments/assets/46de9ba7-10f1-4d8b-8750-d78a64c33003)

These might have been created when resizing the image.

**Comment by javizqh** [comment]
Probably it is because of the resizing. I will try to paint them on top

**Comment by javizqh** [comment]
Can you assure me that the new one is what you wanted?

**Comment by ghost** [comment]
Awesome! Looks much better now, thank you.
