### ISSUE TITLE
[Monte Carlo Laser Loc] bugs in poseToMap

### ISSUE THREAD

**Issue by ghost** [JdeRobot/RoboticsAcademy#2834]
The method `poseToMap` from the [Monte Carlo Laser Localization exercise](https://github.com/JdeRobot/RoboticsAcademy/blob/608da5a8375e40d2061f26f1243fb61dcbd88054/exercises/static/exercises/montecarlo_laser_loc/python_template/ros2_humble/GUI.py#L87) returns floating numbers, which are not valid map coordinates. One would expect to receive the indices of the map cell corresponding to the given pose.

Moreover, the methods `poseToMap` and `mapToPose` are not symmetrical: If one creates a cell in map coordinates, converts it to a pose, and then converts it back to map coordinates, the values are different. You can see an example in this image:

![Screenshot from 2024-11-04 17-09-59](https://github.com/user-attachments/assets/5aa749cf-9878-4245-a238-4adf174996ff)

From the [code related to this functions](https://github.com/JdeRobot/RoboticsAcademy/blob/608da5a8375e40d2061f26f1243fb61dcbd88054/exercises/static/exercises/montecarlo_laser_loc/python_template/ros2_humble/GUI.py#L87-L97), I see that the offset applied when doing the transformation is not the same in both directions:
```Python
    def poseToMap(self, x_prime, y_prime, yaw_prime):
        x = 101.1 * ( 4.2 + y_prime)
        y = 101.1  * ( 5.7 - x_prime)
        yaw = yaw_prime + math.pi/2
        return [x, y, yaw]


    def mapToPose(self, map_x, map_y, map_yaw):
        x = (map_y - 576.27) / -101.1
        y = (map_x - 425.25) /  101.1
        yaw = map_yaw - math.pi/2
        return [x, y, yaw]
```

I don't know where do these numbers come from, so I don't know which one is the correct offset. Could you please fix this?

**Comment by javizqh** [comment]
Thanks for noticing, the error was that 425.25 was the for the old map. Now it is 424.62 (4.2 * 101.1).
