### ISSUE TITLE
[GPU Acceleration] Validate AMD GPU usage and evaluate acceleration

### ISSUE THREAD

**Issue by dpascualhe** [JdeRobot/RoboticsAcademy#2836]
The initial task is to validate whether an AMD GPU can function similarly to Intel cards by using the appropriate DRI path. To test this:
- **GPU acceleration**: 
```shell
docker run --rm -it --device /dev/dri -e DRI_NAME=<AMD card ID> -p 7164:7164 -p 6080:6080 -p 1108:1108 -p 7163:7163 jderobot/robotics-backend
```
- **CPU only**:
```shell
docker run --rm -it -p 7164:7164 -p 6080:6080 -p 1108:1108 -p 7163:7163 jderobot/robotics-backend
```
We aim to capture RTF (Real-Time Factor) and CPU/GPU usage metrics. (@dduro2020)

Next, we can explore using ROCm to determine if it provides further improvements in GPU acceleration. For more details, refer to the [ROCm Docker Containers Guide](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/docker.html).

**Comment by dduro2020** [comment]
Here are the outputs after testing with both commands:

![Screenshot from 2024-11-12 01-18-17](https://github.com/user-attachments/assets/4c5bbcb2-45a7-42e2-b0a7-c33a7817ece3)
