### ISSUE TITLE
car_junction moved to ROS

### ISSUE THREAD

**Issue by kurshakuz** [JdeRobot/RoboticsAcademy#287]
Hello, everyone!

I have slightly modified the _car_junction_ exercise, so that it is now fully ROS compatible. It can be now ran with rosrun world created by @fqez, python init script, and controlled by the modifiable MyAlgorithm script. The visualization can be seen below:
![Screenshot from 2019-03-22 19-20-34](https://user-images.githubusercontent.com/28868430/54825419-b7fcfa00-4cd7-11e9-922c-c272d913c8ea.png)

UPD. I have finally finished the integration and have checked it with the PabloMorenoVera's solution. Now you can see it in the screenshot below:

![Screenshot from 2019-03-23 16-03-35](https://user-images.githubusercontent.com/28868430/54864817-85f6a100-4d86-11e9-90c4-c52e0524568d.png)

I have made a PR a would be happy if you can review it. I have left it with the solution for now so you can see that it works properly.
https://github.com/JdeRobot/RoboticsAcademy/pull/288

**Comment by cawadall** [comment]
closed via #288
