### ISSUE TITLE
[Monaco Editor] The editor doesn't have a way to let the users know of hidden features

### ISSUE THREAD

**Issue by pawanw17** [JdeRobot/RoboticsAcademy#2873]
The Monaco editor has ctrl + scroll up/down mapped to increase/decrease the size of text. There should be some way to let users know of this feature. 

The old editor had +,- buttons on the editor.

![image](https://github.com/user-attachments/assets/8d50745d-f960-4aae-87d5-8152b513a0d8)

**Comment by jmplaza** [comment]
What about an "info button"? Similar to the one we recently added to Unibotics (top right, blue button with the "i")
![info-button-U](https://github.com/user-attachments/assets/35379572-d0c4-4fba-a05c-c0e5e2cfc5fb)
It leads to a webpage with the quick useful user documentation
