### ISSUE TITLE
After a collision, the robot's pose is misaligned

### ISSUE THREAD

**Issue by dduro2020** [JdeRobot/RoboticsAcademy#2908]
![image](https://github.com/user-attachments/assets/1472c35c-e28a-4099-ab52-00b6e8bfc8bb)

**Comment by javizqh** [comment]
It is also misaligned at the start
![Screenshot from 2024-12-11 22-16-11](https://github.com/user-attachments/assets/23b5f4bf-db2b-4b8f-b667-5991bdab54fa)

**Comment by javizqh** [comment]
This has already been solved
