### ISSUE TITLE
Follow_line moved to ROS

### ISSUE THREAD

**Issue by pankhurivanjani** [JdeRobot/RoboticsAcademy#291]
Follow_line exercise has been completed and moved to ROS. I have opened a new pull request in [Link](https://github.com/JdeRobot/RoboticsAcademy/pull/290) 
README.md file had certain errors which have been corrected.
![image](https://user-images.githubusercontent.com/28755817/54944697-1cc78700-4f5a-11e9-8ae2-666a883e2a89.png)
![image](https://user-images.githubusercontent.com/28755817/54944741-349f0b00-4f5a-11e9-99cc-473d20b1743c.png)

A link to solution video is here:
[Link](https://www.youtube.com/watch?v=KYJJEaF4zvE&t=13s)

**Comment by jmplaza** [comment]
Hi @pankhurivanjani , that exercise was already ready for ROS!. 

Looking at your #290 pull-request, the small corrections to the README are fine, but the idea is not to include in the repo any reference solution, like the one you are providing on that pull-request, so each student has to develop her own solution :-)

Just remove your solution from the pull-request and it can be merged, just correcting some of the sentences of the README file.
