### ISSUE TITLE
unable to parse model.config for model

### ISSUE THREAD

**Issue by abhiMishra98** [JdeRobot/RoboticsAcademy#292]
I have been trying to solve this but each time i am getting the same error. Moreover, the world is not getting loaded. Please help.

![23](https://user-images.githubusercontent.com/43945382/55032364-b7959380-5036-11e9-9cbf-bc0bb655f5b8.png)

![24](https://user-images.githubusercontent.com/43945382/55032368-b95f5700-5036-11e9-9f17-453ec6461c23.png)

**Comment by pankhurivanjani** [comment]
Hi @abhiMishra98 have u tried upgrading jderobot-gazebo-assets?

**Comment by jmplaza** [comment]
All the dependencies of FollowLine exercise are now properly included in the current RADI and they work fine in RoboticsAcademy 2.3 release.
