### ISSUE TITLE
more instructions needed in README.md

### ISSUE THREAD

**Issue by ac-optimus** [JdeRobot/RoboticsAcademy#293]
Hi,
I think these instructions should be added ![image](https://user-images.githubusercontent.com/26172160/55117322-71acfe00-5110-11e9-80ac-dec78287e1c9.png)
before 
![image](https://user-images.githubusercontent.com/26172160/55117398-b769c680-5110-11e9-9338-194c32fcdb39.png)

While following the installation I was not able to run ```sudo apt install jderobot-gazebo-assets```
but after following the instructions given on [link](http://jderobot.org/Installation) I was able to run it successfully.
Please guide me if I am missing something,

**Comment by igarag** [comment]
All the documentation has been migrated to GitHub Pages.

Please, review the new documentation about installation in [this link](https://jderobot.github.io/RoboticsAcademy/installation/) and tell us results.

Thanks.
