### ISSUE TITLE
Unable to execute Docker image. 

### ISSUE THREAD

**Issue by PaulNicolasHunter** [JdeRobot/RoboticsAcademy#299]
I'm trying to follow the exercises in the **RobotocsAcademy** (follow_road to be specific).
I'm getting problem running the **world** exec as stated in the Readme.

here is the screen shot of it.

![](https://user-images.githubusercontent.com/26624903/55562384-6f026800-5711-11e9-995d-e6e493c0b1e7.png)

I also looked at the JdeRobot's docker directory, couldn't find anything with **world**, 
what I'm missing here?

**Comment by Pravin854** [comment]
Did you solve it ? I'm also getting same error for `sudo docker run -tiP --rm -p 7681:7681 jderobot/jderobot world  quadrotor_1_roadtextures.world`

**Comment by PaulNicolasHunter** [comment]
@Pravin854 nope, but I tried to follow their instructions in [their docker profile](https://hub.docker.com/r/jderobot/jderobot/), but still no luck, 

![Screenshot from 2019-04-06 18-13-02](https://user-images.githubusercontent.com/26624903/55669693-16110c00-5898-11e9-88dc-4f094615aca7.png)

**Comment by jmplaza** [comment]
Current RADI (docker image) runs fine with all the dependencies of FollowLine exercise and the Gazebo world is launched without problems.
