### ISSUE TITLE
docker error - world not found

### ISSUE THREAD

**Issue by Pravin854** [JdeRobot/RoboticsAcademy#302]
I'm getting the error shown below while running `sudo docker run -tiP --rm -p 7681:7681 jderobot/jderobot world  quadrotor_1_roadtextures.world` on my PC.

![Screenshot from 2019-04-06 10-34-16](https://user-images.githubusercontent.com/23055963/55665149-b430b200-5857-11e9-8d34-df7d4e18f0ae.png)

**Comment by PaulNicolasHunter** [comment]
@Pravin854 I just ran the world without docker. check [this out](https://github.com/JdeRobot/RoboticsAcademy/tree/master/exercises/follow_line) for more information. :)
