### ISSUE TITLE
Launch file for turtlebot line follower exercise not found

### ISSUE THREAD

**Issue by pankhurivanjani** [JdeRobot/RoboticsAcademy#309]
There is no file named 'turtlebot-xtion-followline.launch' in the path /opt/jderobot/share/jderobot/gazebo/launch/turtlebot-xtion-followline.launch provided in Readme instructions.
But there is a file named 'kobuki_1_followlinextion.launch' with the same environment and turtlebot.

I have created a PR [#310](https://github.com/JdeRobot/RoboticsAcademy/pull/310) for the same.

**Comment by cawadall** [comment]
closed via #310
