### ISSUE TITLE
documentation of the Amazon logistics exercise in RoboticsAcademy github pages

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#335]
@vmartinezf has just finished the first release of the [new web page for RoboticsAcademy](https://jderobot.github.io/RoboticsAcademy/), now fully in GitHub Pages!

The idea is that each exercise will have a webpage with its explanation, maybe some illustrative figure and a video of the reference solution

**Comment by kurshakuz** [comment]
Dear @jmplaza,

I added an Amazon Warehouse exercise to the portfolio, please have a look at the https://jderobot.github.io/RoboticsAcademy.

**Comment by jmplaza** [comment]
Well done @kurshakuz !
