### ISSUE TITLE
webpage for each drone exercise at the new RoboticsAcademy web site (in GitHub Pages)

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#336]
@vmartinezf has just finished the first release of the new web page for [RoboticsAcademy](https://jderobot.github.io/RoboticsAcademy), now fully in GitHub Pages!

The idea is that each exercise will have a webpage with its explanation, maybe some illustrative figure and a video of the reference solution (already uploaded at the JdeRobot's YouTube Channel).

Currently we have there three exercises, take a look at [their 'documentation' ](https://github.com/JdeRobot/RoboticsAcademy/tree/master/docs/_portfolio) as an example before adding drone exercises's.

**Comment by igarag** [comment]
It closes. The new website with the documentation has been recently published and is in a growing phase.
