### ISSUE TITLE
[GitHub Pages | Docs] Update docs with the new drone's infrastructure refactoring

### ISSUE THREAD

**Issue by cawadall** [JdeRobot/RoboticsAcademy#344]
The documentation placed on the new JdeRobot WebPage (https://jderobot.github.io/) should be updated with the changes recently integrated through the Drone's ROSifying Patch (#334)

**Comment by jmplaza** [comment]
Solved in #418 and #416 Credits for @pariaspe and @diegomrt Awasame contribution
