### ISSUE TITLE
error while setting up the Gazebo sources

### ISSUE THREAD

**Issue by jiban-jyoti** [JdeRobot/RoboticsAcademy#363]
While running the instruction:
**source /opt/jderobot/share/jderobot/gazebo/gazebo-setup.sh**
![Screenshot from 2019-12-06 13-04-41](https://user-images.githubusercontent.com/44982306/70304911-fe27c880-1828-11ea-817a-724bae7e9513.png)

It is showing no such file or directory. But when I run the command **source /opt/jderobot/share/jderobot/gazebo/gazebo-assets-setup.sh** skipping the first one I was able to run the exercises.
So what is the requirement of the first command when it is running successfully with the second one.

**Comment by jmplaza** [comment]
solved in #369
