### ISSUE TITLE
[ObstacleAvoidance Exercise] Theory and Hints required in Documentation

### ISSUE THREAD

**Issue by SakshayMahna** [JdeRobot/RoboticsAcademy#366]
The documentation of [Obstacle Avoidance Exercise](https://github.com/JdeRobot/RoboticsAcademy/tree/master/exercises/obstacle_avoidance) misses the Theory and Hints along with the instructions to start the formula1 car based exercise.

**Comment by jmplaza** [comment]
Solved in #366
