### ISSUE TITLE
error while executing visualstates for bump and go exercise

### ISSUE THREAD

**Issue by jiban-jyoti** [JdeRobot/RoboticsAcademy#378]
![Screenshot from 2020-01-03 00-15-15](https://user-images.githubusercontent.com/44982306/71668766-2f47da00-2d90-11ea-8c94-30c921c1ce44.png)
While executing ./visualstates.py it is showing an error
sh: 1: /opt/jderobot/bin/getinterfaces.sh: not found

**Comment by jmplaza** [comment]
VisualStates tool has been already deprecated for this exercise. The user now has to program a FSM explicitely in her code
