### ISSUE TITLE
documentation ONLY in the web page, not in the README.md files

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#387]
The web pages are going to be the documentation reference place. For the Academy itself, for each exercise... To avoid mismatches and ease the maintenance the README.md files should include only a link to the corresponding webpage.

In addition, a small recipe about how to deploy the local web server of our web pages (which are based on Jekyll theme Minimal Mistakes) would be useful in the main README.md file. This way contributors may test their changes before submitting a pull-request improving the documentation.

**Comment by igarag** [comment]
Solved in this commit: https://github.com/JdeRobot/RoboticsAcademy/commit/69a341187c77f45e424bb91492707ec479b7482a#diff-e3e2a9bfd88566b05001b02a3f51d286
