### ISSUE TITLE
Error while executing bump and go exercise 

### ISSUE THREAD

**Issue by jiban-jyoti** [JdeRobot/RoboticsAcademy#414]
I tried source installation of visualstates in ubuntu 18.04, ROS Melodic. After doing this I try to run bump and go exercise but I am getting some errors. 

rosrun visualstates main.py
Traceback (most recent call last):
File "/home/jiban/catkin_ws/src/VisualStates/scripts/main.py", line 25, in
from visualstates.gui.visualstates import VisualStates
ImportError: No module named visualstates.gui.visualstates

**Comment by jmplaza** [comment]
VisualStates tool has been already deprecated for this exercise. The user now has to program a FSM explicitely in her code
