### ISSUE TITLE
modify launch files for ROS compatibility

### ISSUE THREAD

**Issue by fqez** [JdeRobot/RoboticsAcademy#454]
Some of the current launch files are meant to work with the jderobot-assets debian package from the JdeRobot APT repository instead of the ros-melodic-jderobot-assets package. An unification is needed to maintain ONLY the ROS package.

**Comment by jmplaza** [comment]
We are now focused on RoboticsAcademy 2.3, which uses web-based templates. All dependencies are now preinstalled in the RADI (RoboticsAcademy Docker Image). For instance, the assets are typically stored in CustomRobots, Drones and IndustrialRobots repositories, and all of them are preinstalled in the RADI.
