### ISSUE TITLE
[amazon_warehouse] installation

### ISSUE THREAD

**Issue by mohamedsayed18** [JdeRobot/RoboticsAcademy#463]
when I try to run the 
```
$ python2 amazonWarehouse.py amazonMap.conf amazonConf.yml
```
I got this error ImportError: No module named kobuki_msgs.msg
so we need to add this package 
sudo apt-get install ros-melodic-kobuki-msgs
after installation, the script runs fine 
should I add this to the readme, or it is just a special case

**Comment by jmplaza** [comment]
Let's include those dependencies in the Installation recipe of this exercise. @SakshayMahna is working right now on the webpage for this exercise, it will be available soon.

Now the README files are no longer maintained, all the documentation about an Academy exercise is placed only on its webpage. We use GitHub Pages and Jekyll themes (Minimal Mistakes theme) for automatic generation of the webpages from the [docs directory of the repository](https://github.com/JdeRobot/RoboticsAcademy/tree/master/docs). This way the webpages have nice appearance and are under revision control.

For instance, you can see the documentation for the FollowLine exercise [here](https://jderobot.github.io/RoboticsAcademy/exercises/follow_line/), and it is written on this [markdown file](https://github.com/JdeRobot/RoboticsAcademy/blob/master/docs/_pages/exercises/AutonomousCars/follow_line.md) of the docs directory of the repo. 

It seems difficult to deal with Minimal Mistakes Jekyll theme, but it is not. After a while it is pretty easy. There are some [helping directions here](https://github.com/JdeRobot/RoboticsAcademy/blob/master/docs/README.md) to check your changes on the documentation before submitting a pull-request.
