### ISSUE TITLE
laser_loc/MyAlgorithm.py shows indentation error

### ISSUE THREAD

**Issue by ayushmankumar7** [JdeRobot/RoboticsAcademy#469]

**Comment by dgvsnl** [comment]
Is there an issue or this issues has already been closed

**Comment by jmplaza** [comment]
Hi @dgvsnl, this exercise has not been refactored to RoboticsAcademy 2.3 yet. Migrating it is on the mid term roadmap but not in the short term goals, we will create an specific issue for this. Not only to solve the "indentation error".

**Comment by dgvsnl** [comment]
Sorry, for the late reply but I am already on it.
