### ISSUE TITLE
Contribute link directs to an empty Wiki page

### ISSUE THREAD

**Issue by kurshakuz** [JdeRobot/RoboticsAcademy#489]
Contribute link in the Readme directs to and empty wiki page [1]. As all documentation has moved to the Github Pages, the link should probably direct to [2].

[1] https://github.com/JdeRobot/RoboticsAcademy/wiki/Contribute
[2] https://jderobot.github.io/RoboticsAcademy/contribute/

**Comment by jmplaza** [comment]
Fixed in #490 Well done @kurshakuz !
