### ISSUE TITLE
Can the exercises run on ROS Development Studio?  

### ISSUE THREAD

**Issue by NadineFadlallah** [JdeRobot/RoboticsAcademy#491]

**Comment by jmplaza** [comment]
no. ROS Development Studio belongs to TheConstruct enterprise. All the JdeRobot Academy exercises are intended to work on your local installation of ROS and for no commercial purposes,

**Comment by jmplaza** [comment]
Uhm, thinking further about it: yes, you can try there for the challenges as long as it is a ROS environment in the cloud. But the intended software to be produced in GSoC-2020 should run typically on a local installation of ROS and Gazebo.
