### ISSUE TITLE
Update car_junction exercise

### ISSUE THREAD

**Issue by kurshakuz** [JdeRobot/RoboticsAcademy#498]
Currently, car_junction exercise is marked as "Update Pending". Update to support ROS Melodic is required + documentation have to be moved on Github Pages

**Comment by kurshakuz** [comment]
Solved in https://github.com/JdeRobot/RoboticsAcademy/pull/499. However, contribution to the theory part and hints is desired. Any help with it is appreciated.

**Comment by pariaspe** [comment]
Solved in #537  and #539
