### ISSUE TITLE
Obstacle Avoidance: Error interface representation

### ISSUE THREAD

**Issue by dhrodao** [JdeRobot/RoboticsAcademy#505]
I've found an issue with the vector representation, they're representated with a 90 degrees rotation. The error is in /Academy/exercises/obstacle_avoidance/gui/GUI.py
On lines 62, 63, and 64. This is what I did in order to fix it:
62->`self.map.setCarArrow(-cy, cx)`
63->`self.map.setObstaclesArrow(-oy, ox)`
64->`self.map.setAverageArrow(-ay, ax)`

**Comment by jmplaza** [comment]
Fixed in #524
