### ISSUE TITLE
[GitHub Pages] Update PX4 dependencies in Installation instructions

### ISSUE THREAD

**Issue by diegomrt** [JdeRobot/RoboticsAcademy#512]
Building the last PX4 Firmware fails when generating uORB topic headers:
```
[uORB/topics/uORBTopics.hpp] Error 1
```
To solve it, as said [here](https://discuss.px4.io/t/generating-uorb-topic-headers-failed/16016), we must update our PX4 installation recipe to include this new dependency:
```
sudo -H pip install packaging
```

**Comment by jmplaza** [comment]
Fixed in #513
