### ISSUE TITLE
Programming Fundamentals - Exercises

### ISSUE THREAD

**Issue by davidrol6** [JdeRobot/RoboticsAcademy#543]
Folder to store the exercises for the course Programming Fundamentals.

**Comment by dgvsnl** [comment]
I want to contribute to this issue

**Comment by dgvsnl** [comment]
Can you give me some more details.

**Comment by akshat5302** [comment]
I want to contribute to this issue please provide a few more details

**Comment by pariaspe** [comment]
Hi @akshat5302, thanks for your interest but this issue is out of scope

**Comment by akshat5302** [comment]
ok

**Comment by javizqh** [comment]
Deprecated
