### ISSUE TITLE
[GitHub Pages] - Vulnerability in Gemlock

### ISSUE THREAD

**Issue by igarag** [JdeRobot/RoboticsAcademy#546]
Upgrade activesupport to version 5.2.4.3 or later. For example:

In file  `docs/Gemfile.lock`:

```ruby
gem "activesupport", ">= 5.2.4.3"
```

**Comment by trunc8** [comment]
Hi @igarag, the current version in the [Gemfile.lock file](https://github.com/JdeRobot/RoboticsAcademy/blob/2fa686ba205a1c9ce4b9aa0d0ccc091a537fe871/docs/Gemfile.lock#L4) is already 5.2.4.4. Is any upgrade or modification still required?

**Comment by igarag** [comment]
This issue was opened to verify that the update was fully backwards compatible. As you say, the current version is higher.

Thanks for the report! We have closed the issue :-)
