### ISSUE TITLE
error while running catkin build

### ISSUE THREAD

**Issue by abubakrsiddq** [JdeRobot/RoboticsAcademy#576]
![Screenshot from 2020-08-06 15-39-58](https://user-images.githubusercontent.com/48096234/89520294-46a1e680-d7fb-11ea-8191-579f260ca81e.png)

i followed all the steps listed,but im stuck here.
Could you tell me how to resolve this issue

**Comment by SakshayMahna** [comment]
Hello!
From the image it looks like you are trying to run the specific infrastructure installation instructions.

What is the exercise that you are supposed to run?

**Comment by abubakrsiddq** [comment]
i was following instructions given here
https://jderobot.github.io/RoboticsAcademy/installation/

**Comment by jmplaza** [comment]
Please jump to RoboticsAcademy 2.3. It is web-based and all the dependencies are pre-installed in the RADI (=RoboticsAcademy Docker Image). 2.0 and 2.1 releases are no longer supported.
