### ISSUE TITLE
F1 position needs to be changed 

### ISSUE THREAD

**Issue by NayOoLwin5** [JdeRobot/RoboticsAcademy#606]
Inside f1_circuit.world file of follow line web-template directory,the pose is **53.462 -10.734 0.004 0 0 -1.57** which shows the following 
![Screenshot from 2020-09-25 05-24-36](https://user-images.githubusercontent.com/52243229/94212454-beb78f00-fec3-11ea-96d3-d776364ecc7f.png)
It needs to be changed to **53.462 -10.734 0.004 0 0 0** for correct starting position.

**Comment by jmplaza** [comment]
No Pull-Request has been sent or merged to solve this issue...
