### ISSUE TITLE
web browser shows connection closed in follow-line exercise.

### ISSUE THREAD

**Issue by divgup** [JdeRobot/RoboticsAcademy#625]
This is terminal screenshot
![Screenshot from 2020-10-23 19-32-48](https://user-images.githubusercontent.com/40417579/97013799-1bf83c00-1567-11eb-94ce-fccd5c18391c.png)

Web browser shows on opening index.html
![Screenshot from 2020-10-23 19-33-02](https://user-images.githubusercontent.com/40417579/97013829-29adc180-1567-11eb-9b36-df82b1d0bfe6.png)

Also I tried implementing the instructions that were there 5-6 days ago on the website page to do the follow line exercise with 
web templates. But no simulation window appears as shown in attached video at the exercise page. However connection gets established but no Gazebo simulation  window opened. 

How to resolve the issue?
Thanks in advance

**Comment by NayOoLwin5** [comment]
Hi, assuming your host machine is linux..
Check the websocket_address variable inside `web-template/assets/websocket_address.js` on your local machine. If it is **127.0.0.1** localhost then it  should work fine.

If the problem still persists, try changing to this address **127.0.0.53** which is the address of the local caching stub resolver and through which the docker can communicate too.
Now, the alert should show connection established. Let us know if it works.

**Comment by divgup** [comment]
Hi @NayOoLwin5 
Now both the address(127.0.0.1 and 127.0.0.53) are working perfectly fine. I don't know what was the problem before.
Thanks
