### ISSUE TITLE
[WebTemplates] Reset and Pause Button not working

### ISSUE THREAD

**Issue by SakshayMahna** [JdeRobot/RoboticsAcademy#634]
The features of the Reset Button are:

- Reset robot to it's start position
- Reset GUI interface corresponding to start position(Not Working)
- Retain the code written by User

The features of the Pause Button are:

- Stop the code running in the robot brain
- Pause the time(Not Working)

**Comment by Jovian-Dsouza** [comment]
Hi , I still have the issue of reset and start button. reset button resets the simulation but then the start button is not able to run the code. I have to refresh the WEB UI everytime this happens.

I am using the latest RoboticsAcademy docker image running on ubuntu 18.04
