### ISSUE TITLE
[WebTemplates] Updates to Documentation

### ISSUE THREAD

**Issue by SakshayMahna** [JdeRobot/RoboticsAcademy#638]
There are some updates required on documentation on webpages.

- Docker commands
- Code samples

**Comment by NayOoLwin5** [comment]
I think `manager.py` should be run separately, not with docker run command that way users don't need to remove the container and run it again after running once.

**Comment by SakshayMahna** [comment]
Yes! This is one of the errors currently faced due to current documentation.
