### ISSUE TITLE
I am not able to install ROS packages on my system, Kindly help

### ISSUE THREAD

**Issue by snehal1720** [JdeRobot/RoboticsAcademy#656]
![Capture](https://user-images.githubusercontent.com/69516022/100763144-cc851580-341a-11eb-8f88-1cf81bef2ef3.JPG)
![Capture1](https://user-images.githubusercontent.com/69516022/100763177-d60e7d80-341a-11eb-80ce-e1174693e799.JPG)

**Comment by jmplaza** [comment]
Hi @snehal1720 , that seems a temporary availability problem on debian package repositories, including ROS ones, nothing related to RoboticsAcademy itself. Try again other day. They seem to be up now, anyway.
