### ISSUE TITLE
Can you give me the answer to the exercise?

### ISSUE THREAD

**Issue by QNjeason** [JdeRobot/RoboticsAcademy#663]
Can you give me the answer to the exercise? Because of their own writing, no ideas, can not compare the final effect.

**Comment by jmplaza** [comment]
Hi @QNjeason, 

which exercise? No, we don't provide public solutions to the exercises of RoboticsAcademy, just to avoid plagiarism. We develop a reference solution for each of them and record an illustrative video of it, which is published on the webpage of each exercise. For instance, take a look at [FollowLine exercise webpage](https://jderobot.github.io/RoboticsAcademy/exercises/AutonomousCars/follow_line/#demonstrative-video), or at [Obstacle Avoidance exercise webpage](https://jderobot.github.io/RoboticsAcademy/exercises/AutonomousCars/obstacle_avoidance#demonstrative-video)

In addition, feel free to ask for support and show your own solutions working on the [RoboticsAcademy forum](https://forum.unibotics.org/).

Cheers,
