### ISSUE TITLE
 [Documentation] Update Web Page for Color Filter Exercise

### ISSUE THREAD

**Issue by jessiffmm** [JdeRobot/RoboticsAcademy#683]
Update the Web Page Documentation of the Color Filter Exercise.

**Comment by Ajayjeena** [comment]
How can i do the same can you please help me as i am new here

**Comment by jessiffmm** [comment]
Do you ask about how to do the documentation or how to create the issue?

**Comment by Ajayjeena** [comment]
Yes I'm interested in computer vision and robotics. So I wanna contribute
towards the same and learn latest technologies.

**Comment by jessiffmm** [comment]
Do you participate in jderobot?

**Comment by Ajayjeena** [comment]
No not till now but wanna participate in it.

**Comment by jessiffmm** [comment]
ok, you should talk to jmplaza. It is the person who leads jderobot.

**Comment by Ajayjeena** [comment]
Okk thank you so much for giving me your valuable time.

**Comment by jessiffmm** [comment]
You're welcome! If you need anything else do not hesitate to ask!

**Comment by Ajayjeena** [comment]
Thank you so much . I will ask
