### ISSUE TITLE
[Documentation] The excercises ported to web templates lack documentation for running the gazebo environment.

### ISSUE THREAD

**Issue by pawanw17** [JdeRobot/RoboticsAcademy#685]
For example in http://jderobot.github.io/RoboticsAcademy/exercises/AutonomousCars/follow_line/ 
After running index.html there seems no follow up for gazebo.

1) Add a point to open gazebo on the web by going to 127.0.0.1:8080 or 192.168.99.100:8080 for windows

**Comment by Jovian-Dsouza** [comment]
Hi , The documentation has been updated now.

Here is a summary to start the exercise

```
docker run -it -p 8080:8080 -p 7681:7681 -p 2303:2303 -p 1905:1905 -p 8765:8765 jderobot/robotics-academy python3.8 manager.py
```
then open `RoboticsAcademy/exercises/follow_line/web-template`

Inside `assets\websocket_address.js` , change the variable `websocket_address` to the IP address through which the container is connected. Usually for Linux machine it is 127.0.0.1 and for Windows is 192.168.99.100

Launch the `exercise.html`  web-page. Wait for some time until an alert appears with the message Connection Established
