### ISSUE TITLE
bash: /opt/ros/noetic/setup.bash: No such file or directory

### ISSUE THREAD

**Issue by snehal1720** [JdeRobot/RoboticsAcademy#686]
![Screenshot-20210102135046-734x439](https://user-images.githubusercontent.com/69516022/103453631-d643b680-4d01-11eb-98af-65e82e350b77.png)

bash: /opt/ros/noetic/setup.bash: No such file or directory. How to fix this??

**Comment by pawanw17** [comment]
Did you install ros noetic correctly?

**Comment by jmplaza** [comment]
Hi @snehal1720, 

each exercise requires a set of dependences, as stated in each exercise webpage and in the [general installation webpage](
https://jderobot.github.io/RoboticsAcademy/installation). Currently ROS1-Melodic is the reference distribution for RoboticsAcademy and the only one supported, with a working installation recipe for the dependences of each exercise. There are plans to migration to ROS1-Noetic and even ROS2-Foxy, but they are only prototypes so far. Volunteer developers are welcome there!

In addition, feel free to use the RADI ([RoboticsAcademy Docker Image](https://hub.docker.com/r/jderobot/robotics-academy/tags)) where many dependencies are already pre-installed and ready to use. You may use current RoboticsAcademy from that docker image.

**Comment by pawanw17** [comment]
Hey @jmplaza I can help in the migration, can you create a branch for noetic to submit any future PRs?

**Comment by jmplaza** [comment]
Hi @pawanw17, 

we are in the process of migrating all exercises from current RoboticsAcademy 2.0 or 2.1 (=using ROS nodes in Python as exercise templates) towards 2.3 (=using web based exercise templates). RoboticsAcademy 2.3 uses a Docker Image with all the dependences already preinstalled, currently that RADI has ROS-Melodic inside. All users may download the latest RADI from [dockerhub](https://hub.docker.com/r/jderobot/robotics-academy/tags). Not all the exercises are already migrated to 2.3, just  FollowLine, ObstacleAvoidance, VacuumCleaner and LocalizedVacuumCleaner. 

The best way of contributing is to help in that migration: (a) to get familiar and do betatesting on those four exercises at 2.3, providing feedback here or in the [RoboticsAcademy forum](https://forum.unibotics.org/); (b) migrating new exercises to 2.3 is also a good way of contributing. 

Once we got all the exercises available in 2.3 then we will work on updating RADI from ROS-Melodic to ROS-Noetic.

**Comment by snehal1720** [comment]
I am trying to install ros melodic but I am encountering an error. Kindly see the attached screenshot and help me at the earliest.
![Screenshot from 2021-01-04 14-08-52](https://user-images.githubusercontent.com/69516022/103517040-80a11280-4e97-11eb-9bc5-26743fb94159.png)

**Comment by snehal1720** [comment]
I tried solving this error but I am not able to resolve it. Kindly help.

**Comment by jmplaza** [comment]
Hi @snehal1720 ,

instead of running Robotics-Academy 2.1 (which requires local installation of all the dependences, incluiding ROS-Melodic) you better run 2.3. Check the [new installation instructions](https://jderobot.github.io/RoboticsAcademy/installation/), we have just updated them for 2.3 users.

**Comment by pawanw17** [comment]
Thanks @jmplaza for the insights! will start by beta testing the excercises.

**Comment by jmplaza** [comment]
ROS1 Melodic is the only ROS distribution currently supported. Anyway the users are not required to install it on their computers at all, as it is already preinstalled in the RADI (RoboticsAcademy Docker Image). 

The plan is to shift to ROS1 Noetic inside RADI (and even ROS2 Foxy) after migrating most exercises to RoboticsAcademy 2.3. New RADIs will be created for them.
