### ISSUE TITLE
difficulty in pulling docker image on my system

### ISSUE THREAD

**Issue by snehal1720** [JdeRobot/RoboticsAcademy#710]
![err2](https://user-images.githubusercontent.com/69516022/104752977-601d6600-577d-11eb-85b9-3078f0f121d7.png)

Please resolve my issue and let me if there is any change in the path of the supporting file/directory. I had properly cloned Robotics Academy repository on my local system and also followed all the instructions mentioned in the installation page properly. I tried to resolve this issue from my end, but it didn't work out.
Kindly suggest me how can I fix it.

**Comment by SakshayMahna** [comment]
Hello!

As I can see, the docker image seems to have been pulled successfully. There's a slight problem with your command, it should be `docker run -it -p 8080:8080 -p 7681:7681 -p 2303:2303 -p 1905:1905 -p 8765:8765 jderobot/robotics-academy python3.8 manager.py`, you seem to be missing a `y` in the end.

**Comment by snehal1720** [comment]
thanks .
