### ISSUE TITLE
Create a home page of exercises

### ISSUE THREAD

**Issue by dvalladaresv** [JdeRobot/RoboticsAcademy#756]

**Comment by shreyas2000** [comment]
How should it be different from the exsisting [exercises](http://jderobot.github.io/RoboticsAcademy/exercises/) page. What information needs to be included in it. Do you intend to use it instead of exsisting [exercise](http://jderobot.github.io/RoboticsAcademy/exercises/) page

**Comment by dvalladaresv** [comment]
This issue is to create an html template that allows you to enter the exercises directly. That is to say that you can access from it to the existing exercises.html. 

It is not related to change the web page of the exercises documentation.

**Comment by shreyas2000** [comment]
ok got it!

**Comment by shreyas2000** [comment]
So user runs the docker image on his machine and acesses the exercise from home page of exercise.

**Comment by dvalladaresv** [comment]
Yes, that's the idea
