### ISSUE TITLE
[DeepLearning] Initial prototype of an exercise about DeepLearning visual object detection

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#767]

**Comment by predator4hack** [comment]
@dpascualhe, can I work with you to work on this task? Since I'm new in RoboticsAcademy,  I'm not sure how to proceed to complete this task. If possible, please assign me some small tasks so that I can learn and follow along with you to solve this task.

**Comment by dpascualhe** [comment]
Duplicated by #990 and solved
