### ISSUE TITLE
Error while Installing JdeRobot-base.

### ISSUE THREAD

**Issue by Spnetic-5** [JdeRobot/RoboticsAcademy#789]
https://jderobot.github.io/RoboticsAcademy/installation/
Err:3 http://wiki.jderobot.org/apt bionic InRelease                                                                                                           
  Could not connect to wiki.jderobot.org:80 (193.147.79.60). - connect (111: Connection refused)

**Comment by jmplaza** [comment]
Hi @Spnetic-5,

JdeRobot-base is a dependency of RoboticsAcademy 2.0 and 2.1, but they are now both deprecated. We are working on 2.3 RoboticsAcademy, with its web-based design. Feel free to start using any of the six exercises available in RoboticsAcademy 2.3: https://jderobot.github.io/RoboticsAcademy/exercises/

Please read the documentation (https://jderobot.github.io/RoboticsAcademy/installation/) and use the RoboticsAcademy forum (https://forum.jderobot.org/c/english/roboticsacademy/12) for comments and discussions. 

Cheers,
