### ISSUE TITLE
new RADI-4.0.0 for ROS2 

### ISSUE THREAD

**Issue by pankhurivanjani** [JdeRobot/RoboticsAcademy#796]
@shreyasgokhale, This will enable us to move forward with our amazon warehouse robot exercise plans

**Comment by Jovian-Dsouza** [comment]
> @shreyasgokhale, This will enable us to move forward with our amazon warehouse robot exercise plans

Cool , I was also thinking of working on the same.

**Comment by jmplaza** [comment]
This RADI will be numbered as RADI-4.x.y. The convention is RADI-2.x.y for RADIs with ROS-Melodic inside (and Gazebo 9); and RADI-3.x.y for RADIs with ROS-Noetic (and Gazebo 11) inside.

**Comment by trunc8** [comment]
Solved and tested below after merging the PR and building from the parent branch.

![image](https://user-images.githubusercontent.com/50488330/124136917-d4856080-daa2-11eb-8337-7bdcd300b0a3.png)
