### ISSUE TITLE
better light in the scenario of "Visual 3D reconstruction" exercise

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#798]
so the objects in front on the robot appear brighter in the robot camera images

**Comment by Suhas-G** [comment]
@dvalladaresv If you haven't started working on this, can I attempt this?

**Comment by dvalladaresv** [comment]
Hello @Suhas-G , I was already working on it, I will do the PR very soon. If you want to see the changes I have made, they are in the issue-798 branch. I have simply changed the light in the world. Any comments or improvements are welcome!

**Comment by Suhas-G** [comment]
Ah ok, no problem. I wanted to work on something related to Gazebo so I asked.

**Comment by jmplaza** [comment]
Hi @Suhas-G you may work on exploring Gazebo-11 in #814
