### ISSUE TITLE
Refactor web templates to share common parts

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#813]
This way, the exercise.html of many exercises will share common widgets, assets and pieces of JS code.

**Comment by jmplaza** [comment]
For instance ws_code.js file

**Comment by jmplaza** [comment]
The long term solution for this will come with the refactoring of all exercise frontend from vanillaJS to ReactJS.

Meanwhile exploring the symlinks may be a good fix. This way all the exercise will have a "base.html" on their directories, but they all will point to a base.html in "RoboticsAcademy/exercise/assets"... It should work for Linux, Windows and MacOS operating systems. That is a requirement. What do you think about this possibility @SakshayMahna @dvalladaresv ?

**Comment by SakshayMahna** [comment]
But, would the symlinks that are generated for a Linux machine work on a Windows machine or vice versa. From what I read, the symlink generation for both seems different, [this link](https://superuser.com/questions/528753/convert-linux-symlinks-to-windows-symlinks). 

Not sure, but can we have a look at .tpl files? Here is a [link](https://stackoverflow.com/questions/1808294/what-are-tpl-files-php-web-design)
