### ISSUE TITLE
[ColorFilter] the instructions for launching the RADI are outdated

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#816]
no editing of "assets\websocket_address.js" is required anymore.

**Comment by RUFFY-369** [comment]
But the websocket_address in the .js file is for linux machine as mentioned in the instructions. What about Windows?

**Comment by RUFFY-369** [comment]
I think it would be better to edit the instructions regarding the address for the Windows User accordingly (whether VM or WSL) to clear the confusion
