### ISSUE TITLE
Different parameter names in drone/HAL.set_cmd_vel/pos/mix for 'yaw' & 'yaw_rate' for drone exercises

### ISSUE THREAD

**Issue by RUFFY-369** [JdeRobot/RoboticsAcademy#817]
In the API instructions' section of drones exercises the parameter name for yaw & yaw_rate is 'az' for all the three drone/HAL.set_cmd_vel/pos/mix() drone control calls, which has not been mentioned in the doc leading to confusion for accessing parameters by name. 

![scrt](https://user-images.githubusercontent.com/66624139/113529899-579d3480-95e2-11eb-8a5c-df24abea0018.png)

**Comment by RUFFY-369** [comment]
I had proposed a solution via PR.

**Comment by pariaspe** [comment]
Merged in #818. Thanks @RUFFY-369
