### ISSUE TITLE
[RADI] Update RADI to 0.3.14

### ISSUE THREAD

**Issue by pariaspe** [JdeRobot/RoboticsAcademy#836]
To include follow_turtlebot exercise

**Comment by trunc8** [comment]
Hi @pariaspe, this is something I am keen to learn! Would I have the authorization to push the updated tag to RobotAcademy's DockerHub image?

**Comment by jmplaza** [comment]
Hi @trunc8 , I'm afraid not. That is only for committers, long term RoboticsAcademy developers

**Comment by trunc8** [comment]
Got it! I shall wait for my turn :)
I also suspected the RELEASE file at the root directory may be tied to an automation script that pushes the Docker image. Is that the case?

**Comment by SakshayMahna** [comment]
Latest Tag: https://hub.docker.com/layers/jderobot/robotics-academy/latest/images/sha256-eb2cf69b0448f965607efdb193ea89a1d35deb677e985303f7a44690d491adee?context=repo

0.3.14 Tag: https://hub.docker.com/layers/jderobot/robotics-academy/0.3.14/images/sha256-eb2cf69b0448f965607efdb193ea89a1d35deb677e985303f7a44690d491adee?context=repo
