### ISSUE TITLE
Connection established popup needs to be clicked twice

### ISSUE THREAD

**Issue by trunc8** [JdeRobot/RoboticsAcademy#845]
The browser alert for "Connection established" or "Connection lost" requires the "OK" button to be clicked twice every time.
![image](https://user-images.githubusercontent.com/50488330/114265704-f5906500-9a0f-11eb-8ff7-09cb7effe57d.png)

**Comment by shreyas2000** [comment]
Could it be more of a feature than an issue , as it's conforming that connection to both websockets  :1905 and :2303 are established sucessfully . Although we can change it give a single alert after both connections are made.

**Comment by trunc8** [comment]
Ahh, it's due to the two VNC connections. It's unlikely to be a feature, else the alert messages would be more verbose. It's also a little annoying for a user to click twice every time.

**Comment by dgvsnl** [comment]
So what now, should we reduce it to one or make it verbose
