### ISSUE TITLE
[Follow Road] Migration to RoboticsAcademy 2.3

### ISSUE THREAD

**Issue by RUFFY-369** [JdeRobot/RoboticsAcademy#859]
I have pushed #860 the migrated version of 'follow_road' to recreate & check for the error occuring during launching & connecting with exercise.html. If the error is resolved the migration can be further improved. Currently, I am trying to resolve the error so, it would be better if someone can also help me regarding it for faster migration
![Screenshot from 2021-04-15 17-07-21](https://user-images.githubusercontent.com/66624139/114864051-273d6d80-9e0e-11eb-9624-527888d532a5.png)

**Comment by iamarkaj** [comment]
Hi @RUFFY-369 It is unable to find polaris_ranger_ev model which is included inside world file

**Comment by iamarkaj** [comment]
Hi @RUFFY-369 it is unable to find polaris_ranger_ev which is included inside world file

**Comment by pariaspe** [comment]
There are still a couple of things to do:

- [ ] Update to last RADI version.
- [ ] Add new models to drones assets.

**Comment by RUFFY-369** [comment]
On it
