### ISSUE TITLE
integration in git of the "Drones: landing on top of  a moving car" exercise

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#9]
First practical exercise at the "advanced programming drones" course. It was developed by @almartinflorido and it would be great to have it integrated in this git repo.

The demo video can be found at  http://jderobot.org/Programacion-avanzada-de-drones#Pr.C3.A1ctica_1:_Aterrizando_encima_de_un_coche

**Comment by nkhedekar** [comment]
The exercise has already been added. (solved in #239)
