### ISSUE TITLE
[drones] Common web-templates for all drone exercises

### ISSUE THREAD

**Issue by iamarkaj** [JdeRobot/RoboticsAcademy#926]

**Comment by iamarkaj** [comment]
Will not this make the development easier? @pariaspe

**Comment by pariaspe** [comment]
What you propose make sense, but I'm not fully convinced. As you have noticed, at least 6 exercises will have the same web template. However, creating a common web-template for drone exercises inside the current common web-template for all the exercises will not be too confusing? I'm not sure if this change will make the development easier.

In my opinion, we should focus on simplicity, even if it means to repeat some code or files. Don't you agree? Other opinions are always welcome :)
