### ISSUE TITLE
[Localized-Vacuum-Cleaner exercise] unify the get position methods

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/RoboticsAcademy#945]
Currently: 
self.pose3d.getPose3d().x - to get the X coordinate of the robot
self.pose3d.getPose3d().y - to get the Y coordinate of the robot
self.pose3d.getPose3d().yaw - to get the orientation of the robot

as stated in [its webpage](https://jderobot.github.io/RoboticsAcademy/exercises/MobileRobots/vacuum_cleaner_loc#api).

It would be better to provide those data in the same way as they are provided in the Obstacle Avoidance exercise, in the HAL:

HAL.getPose3d().x - to get the position of the robot (x coordinate)
HAL.getPose3d().y - to obtain the position of the robot (y coordinate)
HAL.getPose3d().yaw - to get the orientation of the robot with regarding the map

as stated in the [Obstacle-Avoidance exercise webpage](https://jderobot.github.io/RoboticsAcademy/exercises/AutonomousCars/obstacle_avoidance#using-the-interface)

**Comment by ReyDoran** [comment]
Solved in commit [e4f8437d65a40f0de1a409bb81b90480f4e6dffc](https://github.com/JdeRobot/RoboticsAcademy/commit/e4f8437d65a40f0de1a409bb81b90480f4e6dffc)
