### ISSUE TITLE
[DL Digit Classifier] Make consistency policy dependent on framerate during inference for digit classification exercise

### ISSUE THREAD

**Issue by dpascualhe** [JdeRobot/RoboticsAcademy#966]
Currently, the same digit has to be classified during N consecutive frames in order to appear as detected in the GUI. Using a fixed number of frames might result in very different behaviors depending on the resources of the machine in which the exercise is running on. By making this policy dependent on the framerate we will alleviate undesired effects. @shashwat623 

https://github.com/JdeRobot/RoboticsAcademy/blob/76aeab680f443bc4aec53e48c34a9d84cd32b497/exercises/static/exercises/dl_digit_classifier/web-template/exercise.py#L103-L115

**Comment by shashwat623** [comment]
@dpascualhe I've opened a PR for this #981
