### ISSUE TITLE
[RADI-noetic] The drone exercises are not working

### ISSUE THREAD

**Issue by iamarkaj** [JdeRobot/RoboticsAcademy#977]

**Comment by iamarkaj** [comment]
At present, the iris models are spawned correctly but the drone does not take off through the Hardware Abstraction Layer (HAL) takeoff method. The change mode command is reporting "temporally rejected".

**Comment by pariaspe** [comment]
Fixed in JdeRobot/drones#125 and #1051. Waiting for changes to merge and close.
